#pragma once

#include <string>
#include <unordered_map>

enum class MoveName {
    None,
    Pound,
    KarateChop,
    DoubleSlap,
    CometPunch,
    MegaPunch,
    PayDay,
    FirePunch,
    IcePunch,
    ThunderPunch,
    Scratch,
    ViceGrip,
    Guillotine,
    RazorWind,
    SwordsDance,
    Cut,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Bind,
    Slam,
    VineWhip,
    Stomp,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    SandAttack,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    PoisonSting,
    Twineedle,
    PinMissile,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Acid,
    Ember,
    Flamethrower,
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    IceBeam,
    Blizzard,
    Psybeam,
    BubbleBeam,
    AuroraBeam,
    HyperBeam,
    Peck,
    DrillPeck,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Absorb,
    MegaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    StringShot,
    DragonRage,
    FireSpin,
    ThunderShock,
    Thunderbolt,
    ThunderWave,
    Thunder,
    RockThrow,
    Earthquake,
    Fissure,
    Dig,
    Toxic,
    Confusion,
    Psychic,
    Hypnosis,
    Meditate,
    Agility,
    QuickAttack,
    Rage,
    Teleport,
    NightShade,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Harden,
    Minimize,
    Smokescreen,
    ConfuseRay,
    Withdraw,
    DefenseCurl,
    Barrier,
    LightScreen,
    Haze,
    Reflect,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    SelfDestruct,
    EggBomb,
    Lick,
    Smog,
    Sludge,
    BoneClub,
    FireBlast,
    Waterfall,
    Clamp,
    Swift,
    SkullBash,
    SpikeCannon,
    Constrict,
    Amnesia,
    Kinesis,
    SoftBoiled,
    HighJumpKick,
    Glare,
    DreamEater,
    PoisonGas,
    Barrage,
    LeechLife,
    LovelyKiss,
    SkyAttack,
    Transform,
    Bubble,
    DizzyPunch,
    Spore,
    Flash,
    Psywave,
    Splash,
    AcidArmor,
    Crabhammer,
    Explosion,
    FurySwipes,
    Bonemerang,
    Rest,
    RockSlide,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    Struggle,
    Sketch,
    TripleKick,
    Thief,
    SpiderWeb,
    MindReader,
    Nightmare,
    FlameWheel,
    Snore,
    Curse,
    Flail,
    Conversion2,
    Aeroblast,
    CottonSpore,
    Reversal,
    Spite,
    PowderSnow,
    Protect,
    MachPunch,
    ScaryFace,
    FeintAttack,
    SweetKiss,
    BellyDrum,
    SludgeBomb,
    MudSlap,
    Octazooka,
    Spikes,
    ZapCannon,
    Foresight,
    DestinyBond,
    PerishSong,
    IcyWind,
    Detect,
    BoneRush,
    LockOn,
    Outrage,
    Sandstorm,
    GigaDrain,
    Endure,
    Charm,
    Rollout,
    FalseSwipe,
    Swagger,
    MilkDrink,
    Spark,
    FuryCutter,
    SteelWing,
    MeanLook,
    Attract,
    SleepTalk,
    HealBell,
    Return,
    Present,
    Frustration,
    Safeguard,
    PainSplit,
    SacredFire,
    Magnitude,
    DynamicPunch,
    Megahorn,
    DragonBreath,
    BatonPass,
    Encore,
    Pursuit,
    RapidSpin,
    SweetScent,
    IronTail,
    MetalClaw,
    VitalThrow,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    CrossChop,
    Twister,
    RainDance,
    SunnyDay,
    Crunch,
    MirrorCoat,
    PsychUp,
    ExtremeSpeed,
    AncientPower,
    ShadowBall,
    FutureSight,
    RockSmash,
    Whirlpool,
    BeatUp,
    FakeOut,
    Uproar,
    Stockpile,
    SpitUp,
    Swallow,
    HeatWave,
    Hail,
    Torment,
    Flatter,
    WillOWisp,
    Memento,
    Facade,
    FocusPunch,
    SmellingSalts,
    FollowMe,
    NaturePower,
    Charge,
    Taunt,
    HelpingHand,
    Trick,
    RolePlay,
    Wish,
    Assist,
    Ingrain,
    Superpower,
    MagicCoat,
    Recycle,
    Revenge,
    BrickBreak,
    Yawn,
    KnockOff,
    Endeavor,
    Eruption,
    SkillSwap,
    Imprison,
    Refresh,
    Grudge,
    Snatch,
    SecretPower,
    Dive,
    ArmThrust,
    Camouflage,
    TailGlow,
    LusterPurge,
    MistBall,
    FeatherDance,
    TeeterDance,
    BlazeKick,
    MudSport,
    IceBall,
    NeedleArm,
    SlackOff,
    HyperVoice,
    PoisonFang,
    CrushClaw,
    BlastBurn,
    HydroCannon,
    MeteorMash,
    Astonish,
    WeatherBall,
    Aromatherapy,
    FakeTears,
    AirCutter,
    Overheat,
    OdorSleuth,
    RockTomb,
    SilverWind,
    MetalSound,
    GrassWhistle,
    Tickle,
    CosmicPower,
    WaterSpout,
    SignalBeam,
    ShadowPunch,
    Extrasensory,
    SkyUppercut,
    SandTomb,
    SheerCold,
    MuddyWater,
    BulletSeed,
    AerialAce,
    IcicleSpear,
    IronDefense,
    Block,
    Howl,
    DragonClaw,
    FrenzyPlant,
    BulkUp,
    Bounce,
    MudShot,
    PoisonTail,
    Covet,
    VoltTackle,
    MagicalLeaf,
    WaterSport,
    CalmMind,
    LeafBlade,
    DragonDance,
    RockBlast,
    ShockWave,
    WaterPulse,
    DoomDesire,
    PsychoBoost,
    Roost,
    Gravity,
    MiracleEye,
    WakeUpSlap,
    HammerArm,
    GyroBall,
    HealingWish,
    Brine,
    NaturalGift,
    Feint,
    Pluck,
    Tailwind,
    Acupressure,
    MetalBurst,
    UTurn,
    CloseCombat,
    Payback,
    Assurance,
    Embargo,
    Fling,
    PsychoShift,
    TrumpCard,
    HealBlock,
    WringOut,
    PowerTrick,
    GastroAcid,
    LuckyChant,
    MeFirst,
    Copycat,
    PowerSwap,
    GuardSwap,
    Punishment,
    LastResort,
    WorrySeed,
    SuckerPunch,
    ToxicSpikes,
    HeartSwap,
    AquaRing,
    MagnetRise,
    FlareBlitz,
    ForcePalm,
    AuraSphere,
    RockPolish,
    PoisonJab,
    DarkPulse,
    NightSlash,
    AquaTail,
    SeedBomb,
    AirSlash,
    XScissor,
    BugBuzz,
    DragonPulse,
    DragonRush,
    PowerGem,
    DrainPunch,
    VacuumWave,
    FocusBlast,
    EnergyBall,
    BraveBird,
    EarthPower,
    Switcheroo,
    GigaImpact,
    NastyPlot,
    BulletPunch,
    Avalanche,
    IceShard,
    ShadowClaw,
    ThunderFang,
    IceFang,
    FireFang,
    ShadowSneak,
    MudBomb,
    PsychoCut,
    ZenHeadbutt,
    MirrorShot,
    FlashCannon,
    RockClimb,
    Defog,
    TrickRoom,
    DracoMeteor,
    Discharge,
    LavaPlume,
    LeafStorm,
    PowerWhip,
    RockWrecker,
    CrossPoison,
    GunkShot,
    IronHead,
    MagnetBomb,
    StoneEdge,
    Captivate,
    StealthRock,
    GrassKnot,
    Chatter,
    Judgment,
    BugBite,
    ChargeBeam,
    WoodHammer,
    AquaJet,
    AttackOrder,
    DefendOrder,
    HealOrder,
    HeadSmash,
    DoubleHit,
    RoarOfTime,
    SpacialRend,
    LunarDance,
    CrushGrip,
    MagmaStorm,
    DarkVoid,
    SeedFlare,
    OminousWind,
    ShadowForce,
    NumberOfMoves
};

inline std::string toString(MoveName move) {
    static const std::unordered_map<MoveName, std::string> moveToString = {
        {MoveName::None, "None"},
        {MoveName::Pound, "Pound"},
        {MoveName::KarateChop, "Karate Chop"},
        {MoveName::DoubleSlap, "Double Slap"},
        {MoveName::CometPunch, "Comet Punch"},
        {MoveName::MegaPunch, "Mega Punch"},
        {MoveName::PayDay, "Pay Day"},
        {MoveName::FirePunch, "Fire Punch"},
        {MoveName::IcePunch, "Ice Punch"},
        {MoveName::ThunderPunch, "Thunder Punch"},
        {MoveName::Scratch, "Scratch"},
        {MoveName::ViceGrip, "Vice Grip"},
        {MoveName::Guillotine, "Guillotine"},
        {MoveName::RazorWind, "Razor Wind"},
        {MoveName::SwordsDance, "Swords Dance"},
        {MoveName::Cut, "Cut"},
        {MoveName::Gust, "Gust"},
        {MoveName::WingAttack, "Wing Attack"},
        {MoveName::Whirlwind, "Whirlwind"},
        {MoveName::Fly, "Fly"},
        {MoveName::Bind, "Bind"},
        {MoveName::Slam, "Slam"},
        {MoveName::VineWhip, "Vine Whip"},
        {MoveName::Stomp, "Stomp"},
        {MoveName::DoubleKick, "Double Kick"},
        {MoveName::MegaKick, "Mega Kick"},
        {MoveName::JumpKick, "Jump Kick"},
        {MoveName::RollingKick, "Rolling Kick"},
        {MoveName::SandAttack, "Sand Attack"},
        {MoveName::Headbutt, "Headbutt"},
        {MoveName::HornAttack, "Horn Attack"},
        {MoveName::FuryAttack, "Fury Attack"},
        {MoveName::HornDrill, "Horn Drill"},
        {MoveName::Tackle, "Tackle"},
        {MoveName::BodySlam, "Body Slam"},
        {MoveName::Wrap, "Wrap"},
        {MoveName::TakeDown, "Take Down"},
        {MoveName::Thrash, "Thrash"},
        {MoveName::DoubleEdge, "Double Edge"},
        {MoveName::TailWhip, "Tail Whip"},
        {MoveName::PoisonSting, "Poison Sting"},
        {MoveName::Twineedle, "Twineedle"},
        {MoveName::PinMissile, "Pin Missile"},
        {MoveName::Leer, "Leer"},
        {MoveName::Bite, "Bite"},
        {MoveName::Growl, "Growl"},
        {MoveName::Roar, "Roar"},
        {MoveName::Sing, "Sing"},
        {MoveName::Supersonic, "Supersonic"},
        {MoveName::SonicBoom, "Sonic Boom"},
        {MoveName::Disable, "Disable"},
        {MoveName::Acid, "Acid"},
        {MoveName::Ember, "Ember"},
        {MoveName::Flamethrower, "Flamethrower"},
        {MoveName::Mist, "Mist"},
        {MoveName::WaterGun, "Water Gun"},
        {MoveName::HydroPump, "Hydro Pump"},
        {MoveName::Surf, "Surf"},
        {MoveName::IceBeam, "Ice Beam"},
        {MoveName::Blizzard, "Blizzard"},
        {MoveName::Psybeam, "Psybeam"},
        {MoveName::BubbleBeam, "Bubble Beam"},
        {MoveName::AuroraBeam, "Aurora Beam"},
        {MoveName::HyperBeam, "Hyper Beam"},
        {MoveName::Peck, "Peck"},
        {MoveName::DrillPeck, "Drill Peck"},
        {MoveName::Submission, "Submission"},
        {MoveName::LowKick, "Low Kick"},
        {MoveName::Counter, "Counter"},
        {MoveName::SeismicToss, "Seismic Toss"},
        {MoveName::Strength, "Strength"},
        {MoveName::Absorb, "Absorb"},
        {MoveName::MegaDrain, "Mega Drain"},
        {MoveName::LeechSeed, "Leech Seed"},
        {MoveName::Growth, "Growth"},
        {MoveName::RazorLeaf, "Razor Leaf"},
        {MoveName::SolarBeam, "Solar Beam"},
        {MoveName::PoisonPowder, "Poison Powder"},
        {MoveName::StunSpore, "Stun Spore"},
        {MoveName::SleepPowder, "Sleep Powder"},
        {MoveName::PetalDance, "Petal Dance"},
        {MoveName::StringShot, "String Shot"},
        {MoveName::DragonRage, "Dragon Rage"},
        {MoveName::FireSpin, "Fire Spin"},
        {MoveName::ThunderShock, "Thunder Shock"},
        {MoveName::Thunderbolt, "Thunderbolt"},
        {MoveName::ThunderWave, "Thunder Wave"},
        {MoveName::Thunder, "Thunder"},
        {MoveName::RockThrow, "Rock Throw"},
        {MoveName::Earthquake, "Earthquake"},
        {MoveName::Fissure, "Fissure"},
        {MoveName::Dig, "Dig"},
        {MoveName::Toxic, "Toxic"},
        {MoveName::Confusion, "Confusion"},
        {MoveName::Psychic, "Psychic"},
        {MoveName::Hypnosis, "Hypnosis"},
        {MoveName::Meditate, "Meditate"},
        {MoveName::Agility, "Agility"},
        {MoveName::QuickAttack, "Quick Attack"},
        {MoveName::Rage, "Rage"},
        {MoveName::Teleport, "Teleport"},
        {MoveName::NightShade, "Night Shade"},
        {MoveName::Mimic, "Mimic"},
        {MoveName::Screech, "Screech"},
        {MoveName::DoubleTeam, "Double Team"},
        {MoveName::Recover, "Recover"},
        {MoveName::Harden, "Harden"},
        {MoveName::Minimize, "Minimize"},
        {MoveName::Smokescreen, "Smokescreen"},
        {MoveName::ConfuseRay, "Confuse Ray"},
        {MoveName::Withdraw, "Withdraw"},
        {MoveName::DefenseCurl, "Defense Curl"},
        {MoveName::Barrier, "Barrier"},
        {MoveName::LightScreen, "Light Screen"},
        {MoveName::Haze, "Haze"},
        {MoveName::Reflect, "Reflect"},
        {MoveName::FocusEnergy, "Focus Energy"},
        {MoveName::Bide, "Bide"},
        {MoveName::Metronome, "Metronome"},
        {MoveName::MirrorMove, "Mirror Move"},
        {MoveName::SelfDestruct, "Self Destruct"},
        {MoveName::EggBomb, "Egg Bomb"},
        {MoveName::Lick, "Lick"},
        {MoveName::Smog, "Smog"},
        {MoveName::Sludge, "Sludge"},
        {MoveName::BoneClub, "Bone Club"},
        {MoveName::FireBlast, "Fire Blast"},
        {MoveName::Waterfall, "Waterfall"},
        {MoveName::Clamp, "Clamp"},
        {MoveName::Swift, "Swift"},
        {MoveName::SkullBash, "Skull Bash"},
        {MoveName::SpikeCannon, "Spike Cannon"},
        {MoveName::Constrict, "Constrict"},
        {MoveName::Amnesia, "Amnesia"},
        {MoveName::Kinesis, "Kinesis"},
        {MoveName::SoftBoiled, "Soft Boiled"},
        {MoveName::HighJumpKick, "High Jump Kick"},
        {MoveName::Glare, "Glare"},
        {MoveName::DreamEater, "Dream Eater"},
        {MoveName::PoisonGas, "Poison Gas"},
        {MoveName::Barrage, "Barrage"},
        {MoveName::LeechLife, "Leech Life"},
        {MoveName::LovelyKiss, "Lovely Kiss"},
        {MoveName::SkyAttack, "Sky Attack"},
        {MoveName::Transform, "Transform"},
        {MoveName::Bubble, "Bubble"},
        {MoveName::DizzyPunch, "Dizzy Punch"},
        {MoveName::Spore, "Spore"},
        {MoveName::Flash, "Flash"},
        {MoveName::Psywave, "Psywave"},
        {MoveName::Splash, "Splash"},
        {MoveName::AcidArmor, "Acid Armor"},
        {MoveName::Crabhammer, "Crabhammer"},
        {MoveName::Explosion, "Explosion"},
        {MoveName::FurySwipes, "Fury Swipes"},
        {MoveName::Bonemerang, "Bonemerang"},
        {MoveName::Rest, "Rest"},
        {MoveName::RockSlide, "Rock Slide"},
        {MoveName::HyperFang, "Hyper Fang"},
        {MoveName::Sharpen, "Sharpen"},
        {MoveName::Conversion, "Conversion"},
        {MoveName::TriAttack, "Tri Attack"},
        {MoveName::SuperFang, "Super Fang"},
        {MoveName::Slash, "Slash"},
        {MoveName::Substitute, "Substitute"},
        {MoveName::Struggle, "Struggle"},
        {MoveName::Sketch, "Sketch"},
        {MoveName::TripleKick, "Triple Kick"},
        {MoveName::Thief, "Thief"},
        {MoveName::SpiderWeb, "Spider Web"},
        {MoveName::MindReader, "Mind Reader"},
        {MoveName::Nightmare, "Nightmare"},
        {MoveName::FlameWheel, "Flame Wheel"},
        {MoveName::Snore, "Snore"},
        {MoveName::Curse, "Curse"},
        {MoveName::Flail, "Flail"},
        {MoveName::Conversion2, "Conversion 2"},
        {MoveName::Aeroblast, "Aeroblast"},
        {MoveName::CottonSpore, "Cotton Spore"},
        {MoveName::Reversal, "Reversal"},
        {MoveName::Spite, "Spite"},
        {MoveName::PowderSnow, "Powder Snow"},
        {MoveName::Protect, "Protect"},
        {MoveName::MachPunch, "Mach Punch"},
        {MoveName::ScaryFace, "Scary Face"},
        {MoveName::FeintAttack, "Feint Attack"},
        {MoveName::SweetKiss, "Sweet Kiss"},
        {MoveName::BellyDrum, "Belly Drum"},
        {MoveName::SludgeBomb, "Sludge Bomb"},
        {MoveName::MudSlap, "Mud Slap"},
        {MoveName::Octazooka, "Octazooka"},
        {MoveName::Spikes, "Spikes"},
        {MoveName::ZapCannon, "Zap Cannon"},
        {MoveName::Foresight, "Foresight"},
        {MoveName::DestinyBond, "Destiny Bond"},
        {MoveName::PerishSong, "Perish Song"},
        {MoveName::IcyWind, "Icy Wind"},
        {MoveName::Detect, "Detect"},
        {MoveName::BoneRush, "Bone Rush"},
        {MoveName::LockOn, "Lock On"},
        {MoveName::Outrage, "Outrage"},
        {MoveName::Sandstorm, "Sandstorm"},
        {MoveName::GigaDrain, "Giga Drain"},
        {MoveName::Endure, "Endure"},
        {MoveName::Charm, "Charm"},
        {MoveName::Rollout, "Rollout"},
        {MoveName::FalseSwipe, "False Swipe"},
        {MoveName::Swagger, "Swagger"},
        {MoveName::MilkDrink, "Milk Drink"},
        {MoveName::Spark, "Spark"},
        {MoveName::FuryCutter, "Fury Cutter"},
        {MoveName::SteelWing, "Steel Wing"},
        {MoveName::MeanLook, "Mean Look"},
        {MoveName::Attract, "Attract"},
        {MoveName::SleepTalk, "Sleep Talk"},
        {MoveName::HealBell, "Heal Bell"},
        {MoveName::Return, "Return"},
        {MoveName::Present, "Present"},
        {MoveName::Frustration, "Frustration"},
        {MoveName::Safeguard, "Safeguard"},
        {MoveName::PainSplit, "Pain Split"},
        {MoveName::SacredFire, "Sacred Fire"},
        {MoveName::Magnitude, "Magnitude"},
        {MoveName::DynamicPunch, "Dynamic Punch"},
        {MoveName::Megahorn, "Megahorn"},
        {MoveName::DragonBreath, "Dragon Breath"},
        {MoveName::BatonPass, "Baton Pass"},
        {MoveName::Encore, "Encore"},
        {MoveName::Pursuit, "Pursuit"},
        {MoveName::RapidSpin, "Rapid Spin"},
        {MoveName::SweetScent, "Sweet Scent"},
        {MoveName::IronTail, "Iron Tail"},
        {MoveName::MetalClaw, "Metal Claw"},
        {MoveName::VitalThrow, "Vital Throw"},
        {MoveName::MorningSun, "Morning Sun"},
        {MoveName::Synthesis, "Synthesis"},
        {MoveName::Moonlight, "Moonlight"},
        {MoveName::HiddenPower, "Hidden Power"},
        {MoveName::CrossChop, "Cross Chop"},
        {MoveName::Twister, "Twister"},
        {MoveName::RainDance, "Rain Dance"},
        {MoveName::SunnyDay, "Sunny Day"},
        {MoveName::Crunch, "Crunch"},
        {MoveName::MirrorCoat, "Mirror Coat"},
        {MoveName::PsychUp, "Psych Up"},
        {MoveName::ExtremeSpeed, "Extreme Speed"},
        {MoveName::AncientPower, "Ancient Power"},
        {MoveName::ShadowBall, "Shadow Ball"},
        {MoveName::FutureSight, "Future Sight"},
        {MoveName::RockSmash, "Rock Smash"},
        {MoveName::Whirlpool, "Whirlpool"},
        {MoveName::BeatUp, "Beat Up"},
        {MoveName::FakeOut, "Fake Out"},
        {MoveName::Uproar, "Uproar"},
        {MoveName::Stockpile, "Stockpile"},
        {MoveName::SpitUp, "Spit Up"},
        {MoveName::Swallow, "Swallow"},
        {MoveName::HeatWave, "Heat Wave"},
        {MoveName::Hail, "Hail"},
        {MoveName::Torment, "Torment"},
        {MoveName::Flatter, "Flatter"},
        {MoveName::WillOWisp, "Will O Wisp"},
        {MoveName::Memento, "Memento"},
        {MoveName::Facade, "Facade"},
        {MoveName::FocusPunch, "Focus Punch"},
        {MoveName::SmellingSalts, "Smelling Salts"},
        {MoveName::FollowMe, "Follow Me"},
        {MoveName::NaturePower, "Nature Power"},
        {MoveName::Charge, "Charge"},
        {MoveName::Taunt, "Taunt"},
        {MoveName::HelpingHand, "Helping Hand"},
        {MoveName::Trick, "Trick"},
        {MoveName::RolePlay, "Role Play"},
        {MoveName::Wish, "Wish"},
        {MoveName::Assist, "Assist"},
        {MoveName::Ingrain, "Ingrain"},
        {MoveName::Superpower, "Superpower"},
        {MoveName::MagicCoat, "Magic Coat"},
        {MoveName::Recycle, "Recycle"},
        {MoveName::Revenge, "Revenge"},
        {MoveName::BrickBreak, "Brick Break"},
        {MoveName::Yawn, "Yawn"},
        {MoveName::KnockOff, "Knock Off"},
        {MoveName::Endeavor, "Endeavor"},
        {MoveName::Eruption, "Eruption"},
        {MoveName::SkillSwap, "Skill Swap"},
        {MoveName::Imprison, "Imprison"},
        {MoveName::Refresh, "Refresh"},
        {MoveName::Grudge, "Grudge"},
        {MoveName::Snatch, "Snatch"},
        {MoveName::SecretPower, "Secret Power"},
        {MoveName::Dive, "Dive"},
        {MoveName::ArmThrust, "Arm Thrust"},
        {MoveName::Camouflage, "Camouflage"},
        {MoveName::TailGlow, "Tail Glow"},
        {MoveName::LusterPurge, "Luster Purge"},
        {MoveName::MistBall, "Mist Ball"},
        {MoveName::FeatherDance, "Feather Dance"},
        {MoveName::TeeterDance, "Teeter Dance"},
        {MoveName::BlazeKick, "Blaze Kick"},
        {MoveName::MudSport, "Mud Sport"},
        {MoveName::IceBall, "Ice Ball"},
        {MoveName::NeedleArm, "Needle Arm"},
        {MoveName::SlackOff, "Slack Off"},
        {MoveName::HyperVoice, "Hyper Voice"},
        {MoveName::PoisonFang, "Poison Fang"},
        {MoveName::CrushClaw, "Crush Claw"},
        {MoveName::BlastBurn, "Blast Burn"},
        {MoveName::HydroCannon, "Hydro Cannon"},
        {MoveName::MeteorMash, "Meteor Mash"},
        {MoveName::Astonish, "Astonish"},
        {MoveName::WeatherBall, "Weather Ball"},
        {MoveName::Aromatherapy, "Aromatherapy"},
        {MoveName::FakeTears, "Fake Tears"},
        {MoveName::AirCutter, "Air Cutter"},
        {MoveName::Overheat, "Overheat"},
        {MoveName::OdorSleuth, "Odor Sleuth"},
        {MoveName::RockTomb, "Rock Tomb"},
        {MoveName::SilverWind, "Silver Wind"},
        {MoveName::MetalSound, "Metal Sound"},
        {MoveName::GrassWhistle, "Grass Whistle"},
        {MoveName::Tickle, "Tickle"},
        {MoveName::CosmicPower, "Cosmic Power"},
        {MoveName::WaterSpout, "Water Spout"},
        {MoveName::SignalBeam, "Signal Beam"},
        {MoveName::ShadowPunch, "Shadow Punch"},
        {MoveName::Extrasensory, "Extrasensory"},
        {MoveName::SkyUppercut, "Sky Uppercut"},
        {MoveName::SandTomb, "Sand Tomb"},
        {MoveName::SheerCold, "Sheer Cold"},
        {MoveName::MuddyWater, "Muddy Water"},
        {MoveName::BulletSeed, "Bullet Seed"},
        {MoveName::AerialAce, "Aerial Ace"},
        {MoveName::IcicleSpear, "Icicle Spear"},
        {MoveName::IronDefense, "Iron Defense"},
        {MoveName::Block, "Block"},
        {MoveName::Howl, "Howl"},
        {MoveName::DragonClaw, "Dragon Claw"},
        {MoveName::FrenzyPlant, "Frenzy Plant"},
        {MoveName::BulkUp, "Bulk Up"},
        {MoveName::Bounce, "Bounce"},
        {MoveName::MudShot, "Mud Shot"},
        {MoveName::PoisonTail, "Poison Tail"},
        {MoveName::Covet, "Covet"},
        {MoveName::VoltTackle, "Volt Tackle"},
        {MoveName::MagicalLeaf, "Magical Leaf"},
        {MoveName::WaterSport, "Water Sport"},
        {MoveName::CalmMind, "Calm Mind"},
        {MoveName::LeafBlade, "Leaf Blade"},
        {MoveName::DragonDance, "Dragon Dance"},
        {MoveName::RockBlast, "Rock Blast"},
        {MoveName::ShockWave, "Shock Wave"},
        {MoveName::WaterPulse, "Water Pulse"},
        {MoveName::DoomDesire, "Doom Desire"},
        {MoveName::PsychoBoost, "Psycho Boost"},
        {MoveName::Roost, "Roost"},
        {MoveName::Gravity, "Gravity"},
        {MoveName::MiracleEye, "Miracle Eye"},
        {MoveName::WakeUpSlap, "Wake Up Slap"},
        {MoveName::HammerArm, "Hammer Arm"},
        {MoveName::GyroBall, "Gyro Ball"},
        {MoveName::HealingWish, "Healing Wish"},
        {MoveName::Brine, "Brine"},
        {MoveName::NaturalGift, "Natural Gift"},
        {MoveName::Feint, "Feint"},
        {MoveName::Pluck, "Pluck"},
        {MoveName::Tailwind, "Tailwind"},
        {MoveName::Acupressure, "Acupressure"},
        {MoveName::MetalBurst, "Metal Burst"},
        {MoveName::UTurn, "U-Turn"},
        {MoveName::CloseCombat, "Close Combat"},
        {MoveName::Payback, "Payback"},
        {MoveName::Assurance, "Assurance"},
        {MoveName::Embargo, "Embargo"},
        {MoveName::Fling, "Fling"},
        {MoveName::PsychoShift, "Psycho Shift"},
        {MoveName::TrumpCard, "Trump Card"},
        {MoveName::HealBlock, "Heal Block"},
        {MoveName::WringOut, "Wring Out"},
        {MoveName::PowerTrick, "Power Trick"},
        {MoveName::GastroAcid, "Gastro Acid"},
        {MoveName::LuckyChant, "Lucky Chant"},
        {MoveName::MeFirst, "Me First"},
        {MoveName::Copycat, "Copycat"},
        {MoveName::PowerSwap, "Power Swap"},
        {MoveName::GuardSwap, "Guard Swap"},
        {MoveName::Punishment, "Punishment"},
        {MoveName::LastResort, "Last Resort"},
        {MoveName::WorrySeed, "Worry Seed"},
        {MoveName::SuckerPunch, "Sucker Punch"},
        {MoveName::ToxicSpikes, "Toxic Spikes"},
        {MoveName::HeartSwap, "Heart Swap"},
        {MoveName::AquaRing, "Aqua Ring"},
        {MoveName::MagnetRise, "Magnet Rise"},
        {MoveName::FlareBlitz, "Flare Blitz"},
        {MoveName::ForcePalm, "Force Palm"},
        {MoveName::AuraSphere, "Aura Sphere"},
        {MoveName::RockPolish, "Rock Polish"},
        {MoveName::PoisonJab, "Poison Jab"},
        {MoveName::DarkPulse, "Dark Pulse"},
        {MoveName::NightSlash, "Night Slash"},
        {MoveName::AquaTail, "Aqua Tail"},
        {MoveName::SeedBomb, "Seed Bomb"},
        {MoveName::AirSlash, "Air Slash"},
        {MoveName::XScissor, "X Scissor"},
        {MoveName::BugBuzz, "Bug Buzz"},
        {MoveName::DragonPulse, "Dragon Pulse"},
        {MoveName::DragonRush, "Dragon Rush"},
        {MoveName::PowerGem, "Power Gem"},
        {MoveName::DrainPunch, "Drain Punch"},
        {MoveName::VacuumWave, "Vacuum Wave"},
        {MoveName::FocusBlast, "Focus Blast"},
        {MoveName::EnergyBall, "Energy Ball"},
        {MoveName::BraveBird, "Brave Bird"},
        {MoveName::EarthPower, "Earth Power"},
        {MoveName::Switcheroo, "Switcheroo"},
        {MoveName::GigaImpact, "Giga Impact"},
        {MoveName::NastyPlot, "Nasty Plot"},
        {MoveName::BulletPunch, "Bullet Punch"},
        {MoveName::Avalanche, "Avalanche"},
        {MoveName::IceShard, "Ice Shard"},
        {MoveName::ShadowClaw, "Shadow Claw"},
        {MoveName::ThunderFang, "Thunder Fang"},
        {MoveName::IceFang, "Ice Fang"},
        {MoveName::FireFang, "Fire Fang"},
        {MoveName::ShadowSneak, "Shadow Sneak"},
        {MoveName::MudBomb, "Mud Bomb"},
        {MoveName::PsychoCut, "Psycho Cut"},
        {MoveName::ZenHeadbutt, "Zen Headbutt"},
        {MoveName::MirrorShot, "Mirror Shot"},
        {MoveName::FlashCannon, "Flash Cannon"},
        {MoveName::RockClimb, "Rock Climb"},
        {MoveName::Defog, "Defog"},
        {MoveName::TrickRoom, "Trick Room"},
        {MoveName::DracoMeteor, "Draco Meteor"},
        {MoveName::Discharge, "Discharge"},
        {MoveName::LavaPlume, "Lava Plume"},
        {MoveName::LeafStorm, "Leaf Storm"},
        {MoveName::PowerWhip, "Power Whip"},
        {MoveName::RockWrecker, "Rock Wrecker"},
        {MoveName::CrossPoison, "Cross Poison"},
        {MoveName::GunkShot, "Gunk Shot"},
        {MoveName::IronHead, "Iron Head"},
        {MoveName::MagnetBomb, "Magnet Bomb"},
        {MoveName::StoneEdge, "Stone Edge"},
        {MoveName::Captivate, "Captivate"},
        {MoveName::StealthRock, "Stealth Rock"},
        {MoveName::GrassKnot, "Grass Knot"},
        {MoveName::Chatter, "Chatter"},
        {MoveName::Judgment, "Judgment"},
        {MoveName::BugBite, "Bug Bite"},
        {MoveName::ChargeBeam, "Charge Beam"},
        {MoveName::WoodHammer, "Wood Hammer"},
        {MoveName::AquaJet, "Aqua Jet"},
        {MoveName::AttackOrder, "Attack Order"},
        {MoveName::DefendOrder, "Defend Order"},
        {MoveName::HealOrder, "Heal Order"},
        {MoveName::HeadSmash, "Head Smash"},
        {MoveName::DoubleHit, "Double Hit"},
        {MoveName::RoarOfTime, "Roar Of Time"},
        {MoveName::SpacialRend, "Spacial Rend"},
        {MoveName::LunarDance, "Lunar Dance"},
        {MoveName::CrushGrip, "Crush Grip"},
        {MoveName::MagmaStorm, "Magma Storm"},
        {MoveName::DarkVoid, "Dark Void"},
        {MoveName::SeedFlare, "Seed Flare"},
        {MoveName::OminousWind, "Ominous Wind"},
        {MoveName::ShadowForce, "Shadow Force"}
    };
    return moveToString.at(move);
}
