#pragma once

#include <string>
#include <unordered_map>

enum class PokemonName {
    None,
    Bulbasaur,
    Ivysaur,
    Venusaur,
    Charmander,
    Charmeleon,
    Charizard,
    Squirtle,
    Wartortle,
    Blastoise,
    Caterpie,
    Metapod,
    Butterfree,
    Weedle,
    Kakuna,
    Beedrill,
    Pidgey,
    Pidgeotto,
    Pidgeot,
    Rattata,
    Raticate,
    Spearow,
    Fearow,
    Ekans,
    Arbok,
    Pikachu,
    Raichu,
    Sandshrew,
    Sandslash,
    NidoranF,
    Nidorina,
    Nidoqueen,
    NidoranM,
    Nidorino,
    Nidoking,
    Clefairy,
    Clefable,
    Vulpix,
    Ninetales,
    Jigglypuff,
    Wigglytuff,
    Zubat,
    Golbat,
    Oddish,
    Gloom,
    Vileplume,
    Paras,
    Parasect,
    Venonat,
    Venomoth,
    Diglett,
    Dugtrio,
    Meowth,
    Persian,
    Psyduck,
    Golduck,
    Mankey,
    Primeape,
    Growlithe,
    Arcanine,
    Poliwag,
    Poliwhirl,
    Poliwrath,
    Abra,
    Kadabra,
    Alakazam,
    Machop,
    Machoke,
    Machamp,
    Bellsprout,
    Weepinbell,
    Victreebel,
    Tentacool,
    Tentacruel,
    Geodude,
    Graveler,
    Golem,
    Ponyta,
    Rapidash,
    Slowpoke,
    Slowbro,
    Magnemite,
    Magneton,
    Farfetchd,
    Doduo,
    Dodrio,
    Seel,
    Dewgong,
    Grimer,
    Muk,
    Shellder,
    Cloyster,
    Gastly,
    Haunter,
    Gengar,
    Onix,
    Drowzee,
    Hypno,
    Krabby,
    Kingler,
    Voltorb,
    Electrode,
    Exeggcute,
    Exeggutor,
    Cubone,
    Marowak,
    Hitmonlee,
    Hitmonchan,
    Lickitung,
    Koffing,
    Weezing,
    Rhyhorn,
    Rhydon,
    Chansey,
    Tangela,
    Kangaskhan,
    Horsea,
    Seadra,
    Goldeen,
    Seaking,
    Staryu,
    Starmie,
    MrMime,
    Scyther,
    Jynx,
    Electabuzz,
    Magmar,
    Pinsir,
    Tauros,
    Magikarp,
    Gyarados,
    Lapras,
    Ditto,
    Eevee,
    Vaporeon,
    Jolteon,
    Flareon,
    Porygon,
    Omanyte,
    Omastar,
    Kabuto,
    Kabutops,
    Aerodactyl,
    Snorlax,
    Articuno,
    Zapdos,
    Moltres,
    Dratini,
    Dragonair,
    Dragonite,
    Mewtwo,
    Mew,
    Chikorita,
    Bayleef,
    Meganium,
    Cyndaquil,
    Quilava,
    Typhlosion,
    Totodile,
    Croconaw,
    Feraligatr,
    Sentret,
    Furret,
    Hoothoot,
    Noctowl,
    Ledyba,
    Ledian,
    Spinarak,
    Ariados,
    Crobat,
    Chinchou,
    Lanturn,
    Pichu,
    Cleffa,
    Igglybuff,
    Togepi,
    Togetic,
    Natu,
    Xatu,
    Mareep,
    Flaaffy,
    Ampharos,
    Bellossom,
    Marill,
    Azumarill,
    Sudowoodo,
    Politoed,
    Hoppip,
    Skiploom,
    Jumpluff,
    Aipom,
    Sunkern,
    Sunflora,
    Yanma,
    Wooper,
    Quagsire,
    Espeon,
    Umbreon,
    Murkrow,
    Slowking,
    Misdreavus,
    Unown,
    Wobbuffet,
    Girafarig,
    Pineco,
    Forretress,
    Dunsparce,
    Gligar,
    Steelix,
    Snubbull,
    Granbull,
    Qwilfish,
    Scizor,
    Shuckle,
    Heracross,
    Sneasel,
    Teddiursa,
    Ursaring,
    Slugma,
    Magcargo,
    Swinub,
    Piloswine,
    Corsola,
    Remoraid,
    Octillery,
    Delibird,
    Mantine,
    Skarmory,
    Houndour,
    Houndoom,
    Kingdra,
    Phanpy,
    Donphan,
    Porygon2,
    Stantler,
    Smeargle,
    Tyrogue,
    Hitmontop,
    Smoochum,
    Elekid,
    Magby,
    Miltank,
    Blissey,
    Raikou,
    Entei,
    Suicune,
    Larvitar,
    Pupitar,
    Tyranitar,
    Lugia,
    HoOh,
    Celebi,
    Treecko,
    Grovyle,
    Sceptile,
    Torchic,
    Combusken,
    Blaziken,
    Mudkip,
    Marshtomp,
    Swampert,
    Poochyena,
    Mightyena,
    Zigzagoon,
    Linoone,
    Wurmple,
    Silcoon,
    Beautifly,
    Cascoon,
    Dustox,
    Lotad,
    Lombre,
    Ludicolo,
    Seedot,
    Nuzleaf,
    Shiftry,
    Taillow,
    Swellow,
    Wingull,
    Pelipper,
    Ralts,
    Kirlia,
    Gardevoir,
    Surskit,
    Masquerain,
    Shroomish,
    Breloom,
    Slakoth,
    Vigoroth,
    Slaking,
    Nincada,
    Ninjask,
    Shedinja,
    Whismur,
    Loudred,
    Exploud,
    Makuhita,
    Hariyama,
    Azurill,
    Nosepass,
    Skitty,
    Delcatty,
    Sableye,
    Mawile,
    Aron,
    Lairon,
    Aggron,
    Meditite,
    Medicham,
    Electrike,
    Manectric,
    Plusle,
    Minun,
    Volbeat,
    Illumise,
    Roselia,
    Gulpin,
    Swalot,
    Carvanha,
    Sharpedo,
    Wailmer,
    Wailord,
    Numel,
    Camerupt,
    Torkoal,
    Spoink,
    Grumpig,
    Spinda,
    Trapinch,
    Vibrava,
    Flygon,
    Cacnea,
    Cacturne,
    Swablu,
    Altaria,
    Zangoose,
    Seviper,
    Lunatone,
    Solrock,
    Barboach,
    Whiscash,
    Corphish,
    Crawdaunt,
    Baltoy,
    Claydol,
    Lileep,
    Cradily,
    Anorith,
    Armaldo,
    Feebas,
    Milotic,
    Castform,
    Kecleon,
    Shuppet,
    Banette,
    Duskull,
    Dusclops,
    Tropius,
    Chimecho,
    Absol,
    Wynaut,
    Snorunt,
    Glalie,
    Spheal,
    Sealeo,
    Walrein,
    Clamperl,
    Huntail,
    Gorebyss,
    Relicanth,
    Luvdisc,
    Bagon,
    Shelgon,
    Salamence,
    Beldum,
    Metang,
    Metagross,
    Regirock,
    Regice,
    Registeel,
    Latias,
    Latios,
    Kyogre,
    Groudon,
    Rayquaza,
    Jirachi,
    Deoxys,
    Turtwig,
    Grotle,
    Torterra,
    Chimchar,
    Monferno,
    Infernape,
    Piplup,
    Prinplup,
    Empoleon,
    Starly,
    Staravia,
    Staraptor,
    Bidoof,
    Bibarel,
    Kricketot,
    Kricketune,
    Shinx,
    Luxio,
    Luxray,
    Budew,
    Roserade,
    Cranidos,
    Rampardos,
    Shieldon,
    Bastiodon,
    Burmy,
    Wormadam,
    Mothim,
    Combee,
    Vespiquen,
    Pachirisu,
    Buizel,
    Floatzel,
    Cherubi,
    Cherrim,
    Shellos,
    Gastrodon,
    Ambipom,
    Drifloon,
    Drifblim,
    Buneary,
    Lopunny,
    Mismagius,
    Honchkrow,
    Glameow,
    Purugly,
    Chingling,
    Stunky,
    Skuntank,
    Bronzor,
    Bronzong,
    Bonsly,
    MimeJr,
    Happiny,
    Chatot,
    Spiritomb,
    Gible,
    Gabite,
    Garchomp,
    Munchlax,
    Riolu,
    Lucario,
    Hippopotas,
    Hippowdon,
    Skorupi,
    Drapion,
    Croagunk,
    Toxicroak,
    Carnivine,
    Finneon,
    Lumineon,
    Mantyke,
    Snover,
    Abomasnow,
    Weavile,
    Magnezone,
    Lickilicky,
    Rhyperior,
    Tangrowth,
    Electivire,
    Magmortar,
    Togekiss,
    Yanmega,
    Leafeon,
    Glaceon,
    Gliscor,
    Mamoswine,
    PorygonZ,
    Gallade,
    Probopass,
    Dusknoir,
    Froslass,
    Rotom,
    Uxie,
    Mesprit,
    Azelf,
    Dialga,
    Palkia,
    Heatran,
    Regigigas,
    Giratina,
    Cresselia,
    Phione,
    Manaphy,
    Darkrai,
    Shaymin,
    Arceus,
    NumberOfPokemon
};

inline std::string toString(PokemonName p) {
    static const std::unordered_map<PokemonName, std::string> pokemonToString = {
        {PokemonName::None, "none"},
        {PokemonName::Bulbasaur, "bulbasaur"},
        {PokemonName::Ivysaur, "ivysaur"},
        {PokemonName::Venusaur, "venusaur"},
        {PokemonName::Charmander, "charmander"},
        {PokemonName::Charmeleon, "charmeleon"},
        {PokemonName::Charizard, "charizard"},
        {PokemonName::Squirtle, "squirtle"},
        {PokemonName::Wartortle, "wartortle"},
        {PokemonName::Blastoise, "blastoise"},
        {PokemonName::Caterpie, "caterpie"},
        {PokemonName::Metapod, "metapod"},
        {PokemonName::Butterfree, "butterfree"},
        {PokemonName::Weedle, "weedle"},
        {PokemonName::Kakuna, "kakuna"},
        {PokemonName::Beedrill, "beedrill"},
        {PokemonName::Pidgey, "pidgey"},
        {PokemonName::Pidgeotto, "pidgeotto"},
        {PokemonName::Pidgeot, "pidgeot"},
        {PokemonName::Rattata, "rattata"},
        {PokemonName::Raticate, "raticate"},
        {PokemonName::Spearow, "spearow"},
        {PokemonName::Fearow, "fearow"},
        {PokemonName::Ekans, "ekans"},
        {PokemonName::Arbok, "arbok"},
        {PokemonName::Pikachu, "pikachu"},
        {PokemonName::Raichu, "raichu"},
        {PokemonName::Sandshrew, "sandshrew"},
        {PokemonName::Sandslash, "sandslash"},
        {PokemonName::NidoranF, "nidoranf"},
        {PokemonName::Nidorina, "nidorina"},
        {PokemonName::Nidoqueen, "nidoqueen"},
        {PokemonName::NidoranM, "nidoranm"},
        {PokemonName::Nidorino, "nidorino"},
        {PokemonName::Nidoking, "nidoking"},
        {PokemonName::Clefairy, "clefairy"},
        {PokemonName::Clefable, "clefable"},
        {PokemonName::Vulpix, "vulpix"},
        {PokemonName::Ninetales, "ninetales"},
        {PokemonName::Jigglypuff, "jigglypuff"},
        {PokemonName::Wigglytuff, "wigglytuff"},
        {PokemonName::Zubat, "zubat"},
        {PokemonName::Golbat, "golbat"},
        {PokemonName::Oddish, "oddish"},
        {PokemonName::Gloom, "gloom"},
        {PokemonName::Vileplume, "vileplume"},
        {PokemonName::Paras, "paras"},
        {PokemonName::Parasect, "parasect"},
        {PokemonName::Venonat, "venonat"},
        {PokemonName::Venomoth, "venomoth"},
        {PokemonName::Diglett, "diglett"},
        {PokemonName::Dugtrio, "dugtrio"},
        {PokemonName::Meowth, "meowth"},
        {PokemonName::Persian, "persian"},
        {PokemonName::Psyduck, "psyduck"},
        {PokemonName::Golduck, "golduck"},
        {PokemonName::Mankey, "mankey"},
        {PokemonName::Primeape, "primeape"},
        {PokemonName::Growlithe, "growlithe"},
        {PokemonName::Arcanine, "arcanine"},
        {PokemonName::Poliwag, "poliwag"},
        {PokemonName::Poliwhirl, "poliwhirl"},
        {PokemonName::Poliwrath, "poliwrath"},
        {PokemonName::Abra, "abra"},
        {PokemonName::Kadabra, "kadabra"},
        {PokemonName::Alakazam, "alakazam"},
        {PokemonName::Machop, "machop"},
        {PokemonName::Machoke, "machoke"},
        {PokemonName::Machamp, "machamp"},
        {PokemonName::Bellsprout, "bellsprout"},
        {PokemonName::Weepinbell, "weepinbell"},
        {PokemonName::Victreebel, "victreebel"},
        {PokemonName::Tentacool, "tentacool"},
        {PokemonName::Tentacruel, "tentacruel"},
        {PokemonName::Geodude, "geodude"},
        {PokemonName::Graveler, "graveler"},
        {PokemonName::Golem, "golem"},
        {PokemonName::Ponyta, "ponyta"},
        {PokemonName::Rapidash, "rapidash"},
        {PokemonName::Slowpoke, "slowpoke"},
        {PokemonName::Slowbro, "slowbro"},
        {PokemonName::Magnemite, "magnemite"},
        {PokemonName::Magneton, "magneton"},
        {PokemonName::Farfetchd, "farfetchd"},
        {PokemonName::Doduo, "doduo"},
        {PokemonName::Dodrio, "dodrio"},
        {PokemonName::Seel, "seel"},
        {PokemonName::Dewgong, "dewgong"},
        {PokemonName::Grimer, "grimer"},
        {PokemonName::Muk, "muk"},
        {PokemonName::Shellder, "shellder"},
        {PokemonName::Cloyster, "cloyster"},
        {PokemonName::Gastly, "gastly"},
        {PokemonName::Haunter, "haunter"},
        {PokemonName::Gengar, "gengar"},
        {PokemonName::Onix, "onix"},
        {PokemonName::Drowzee, "drowzee"},
        {PokemonName::Hypno, "hypno"},
        {PokemonName::Krabby, "krabby"},
        {PokemonName::Kingler, "kingler"},
        {PokemonName::Voltorb, "voltorb"},
        {PokemonName::Electrode, "electrode"},
        {PokemonName::Exeggcute, "exeggcute"},
        {PokemonName::Exeggutor, "exeggutor"},
        {PokemonName::Cubone, "cubone"},
        {PokemonName::Marowak, "marowak"},
        {PokemonName::Hitmonlee, "hitmonlee"},
        {PokemonName::Hitmonchan, "hitmonchan"},
        {PokemonName::Lickitung, "lickitung"},
        {PokemonName::Koffing, "koffing"},
        {PokemonName::Weezing, "weezing"},
        {PokemonName::Rhyhorn, "rhyhorn"},
        {PokemonName::Rhydon, "rhydon"},
        {PokemonName::Chansey, "chansey"},
        {PokemonName::Tangela, "tangela"},
        {PokemonName::Kangaskhan, "kangaskhan"},
        {PokemonName::Horsea, "horsea"},
        {PokemonName::Seadra, "seadra"},
        {PokemonName::Goldeen, "goldeen"},
        {PokemonName::Seaking, "seaking"},
        {PokemonName::Staryu, "staryu"},
        {PokemonName::Starmie, "starmie"},
        {PokemonName::MrMime, "mrmime"},
        {PokemonName::Scyther, "scyther"},
        {PokemonName::Jynx, "jynx"},
        {PokemonName::Electabuzz, "electabuzz"},
        {PokemonName::Magmar, "magmar"},
        {PokemonName::Pinsir, "pinsir"},
        {PokemonName::Tauros, "tauros"},
        {PokemonName::Magikarp, "magikarp"},
        {PokemonName::Gyarados, "gyarados"},
        {PokemonName::Lapras, "lapras"},
        {PokemonName::Ditto, "ditto"},
        {PokemonName::Eevee, "eevee"},
        {PokemonName::Vaporeon, "vaporeon"},
        {PokemonName::Jolteon, "jolteon"},
        {PokemonName::Flareon, "flareon"},
        {PokemonName::Porygon, "porygon"},
        {PokemonName::Omanyte, "omanyte"},
        {PokemonName::Omastar, "omastar"},
        {PokemonName::Kabuto, "kabuto"},
        {PokemonName::Kabutops, "kabutops"},
        {PokemonName::Aerodactyl, "aerodactyl"},
        {PokemonName::Snorlax, "snorlax"},
        {PokemonName::Articuno, "articuno"},
        {PokemonName::Zapdos, "zapdos"},
        {PokemonName::Moltres, "moltres"},
        {PokemonName::Dratini, "dratini"},
        {PokemonName::Dragonair, "dragonair"},
        {PokemonName::Dragonite, "dragonite"},
        {PokemonName::Mewtwo, "mewtwo"},
        {PokemonName::Mew, "mew"},
        {PokemonName::Chikorita, "chikorita"},
        {PokemonName::Bayleef, "bayleef"},
        {PokemonName::Meganium, "meganium"},
        {PokemonName::Cyndaquil, "cyndaquil"},
        {PokemonName::Quilava, "quilava"},
        {PokemonName::Typhlosion, "typhlosion"},
        {PokemonName::Totodile, "totodile"},
        {PokemonName::Croconaw, "croconaw"},
        {PokemonName::Feraligatr, "feraligatr"},
        {PokemonName::Sentret, "sentret"},
        {PokemonName::Furret, "furret"},
        {PokemonName::Hoothoot, "hoothoot"},
        {PokemonName::Noctowl, "noctowl"},
        {PokemonName::Ledyba, "ledyba"},
        {PokemonName::Ledian, "ledian"},
        {PokemonName::Spinarak, "spinarak"},
        {PokemonName::Ariados, "ariados"},
        {PokemonName::Crobat, "crobat"},
        {PokemonName::Chinchou, "chinchou"},
        {PokemonName::Lanturn, "lanturn"},
        {PokemonName::Pichu, "pichu"},
        {PokemonName::Cleffa, "cleffa"},
        {PokemonName::Igglybuff, "igglybuff"},
        {PokemonName::Togepi, "togepi"},
        {PokemonName::Togetic, "togetic"},
        {PokemonName::Natu, "natu"},
        {PokemonName::Xatu, "xatu"},
        {PokemonName::Mareep, "mareep"},
        {PokemonName::Flaaffy, "flaaffy"},
        {PokemonName::Ampharos, "ampharos"},
        {PokemonName::Bellossom, "bellossom"},
        {PokemonName::Marill, "marill"},
        {PokemonName::Azumarill, "azumarill"},
        {PokemonName::Sudowoodo, "sudowoodo"},
        {PokemonName::Politoed, "politoed"},
        {PokemonName::Hoppip, "hoppip"},
        {PokemonName::Skiploom, "skiploom"},
        {PokemonName::Jumpluff, "jumpluff"},
        {PokemonName::Aipom, "aipom"},
        {PokemonName::Sunkern, "sunkern"},
        {PokemonName::Sunflora, "sunflora"},
        {PokemonName::Yanma, "yanma"},
        {PokemonName::Wooper, "wooper"},
        {PokemonName::Quagsire, "quagsire"},
        {PokemonName::Espeon, "espeon"},
        {PokemonName::Umbreon, "umbreon"},
        {PokemonName::Murkrow, "murkrow"},
        {PokemonName::Slowking, "slowking"},
        {PokemonName::Misdreavus, "misdreavus"},
        {PokemonName::Unown, "unown"},
        {PokemonName::Wobbuffet, "wobbuffet"},
        {PokemonName::Girafarig, "girafarig"},
        {PokemonName::Pineco, "pineco"},
        {PokemonName::Forretress, "forretress"},
        {PokemonName::Dunsparce, "dunsparce"},
        {PokemonName::Gligar, "gligar"},
        {PokemonName::Steelix, "steelix"},
        {PokemonName::Snubbull, "snubbull"},
        {PokemonName::Granbull, "granbull"},
        {PokemonName::Qwilfish, "qwilfish"},
        {PokemonName::Scizor, "scizor"},
        {PokemonName::Shuckle, "shuckle"},
        {PokemonName::Heracross, "heracross"},
        {PokemonName::Sneasel, "sneasel"},
        {PokemonName::Teddiursa, "teddiursa"},
        {PokemonName::Ursaring, "ursaring"},
        {PokemonName::Slugma, "slugma"},
        {PokemonName::Magcargo, "magcargo"},
        {PokemonName::Swinub, "swinub"},
        {PokemonName::Piloswine, "piloswine"},
        {PokemonName::Corsola, "corsola"},
        {PokemonName::Remoraid, "remoraid"},
        {PokemonName::Octillery, "octillery"},
        {PokemonName::Delibird, "delibird"},
        {PokemonName::Mantine, "mantine"},
        {PokemonName::Skarmory, "skarmory"},
        {PokemonName::Houndour, "houndour"},
        {PokemonName::Houndoom, "houndoom"},
        {PokemonName::Kingdra, "kingdra"},
        {PokemonName::Phanpy, "phanpy"},
        {PokemonName::Donphan, "donphan"},
        {PokemonName::Porygon2, "porygon2"},
        {PokemonName::Stantler, "stantler"},
        {PokemonName::Smeargle, "smeargle"},
        {PokemonName::Tyrogue, "tyrogue"},
        {PokemonName::Hitmontop, "hitmontop"},
        {PokemonName::Smoochum, "smoochum"},
        {PokemonName::Elekid, "elekid"},
        {PokemonName::Magby, "magby"},
        {PokemonName::Miltank, "miltank"},
        {PokemonName::Blissey, "blissey"},
        {PokemonName::Raikou, "raikou"},
        {PokemonName::Entei, "entei"},
        {PokemonName::Suicune, "suicune"},
        {PokemonName::Larvitar, "larvitar"},
        {PokemonName::Pupitar, "pupitar"},
        {PokemonName::Tyranitar, "tyranitar"},
        {PokemonName::Lugia, "lugia"},
        {PokemonName::HoOh, "hooh"},
        {PokemonName::Celebi, "celebi"},
        {PokemonName::Treecko, "treecko"},
        {PokemonName::Grovyle, "grovyle"},
        {PokemonName::Sceptile, "sceptile"},
        {PokemonName::Torchic, "torchic"},
        {PokemonName::Combusken, "combusken"},
        {PokemonName::Blaziken, "blaziken"},
        {PokemonName::Mudkip, "mudkip"},
        {PokemonName::Marshtomp, "marshtomp"},
        {PokemonName::Swampert, "swampert"},
        {PokemonName::Poochyena, "poochyena"},
        {PokemonName::Mightyena, "mightyena"},
        {PokemonName::Zigzagoon, "zigzagoon"},
        {PokemonName::Linoone, "linoone"},
        {PokemonName::Wurmple, "wurmple"},
        {PokemonName::Silcoon, "silcoon"},
        {PokemonName::Beautifly, "beautifly"},
        {PokemonName::Cascoon, "cascoon"},
        {PokemonName::Dustox, "dustox"},
        {PokemonName::Lotad, "lotad"},
        {PokemonName::Lombre, "lombre"},
        {PokemonName::Ludicolo, "ludicolo"},
        {PokemonName::Seedot, "seedot"},
        {PokemonName::Nuzleaf, "nuzleaf"},
        {PokemonName::Shiftry, "shiftry"},
        {PokemonName::Taillow, "taillow"},
        {PokemonName::Swellow, "swellow"},
        {PokemonName::Wingull, "wingull"},
        {PokemonName::Pelipper, "pelipper"},
        {PokemonName::Ralts, "ralts"},
        {PokemonName::Kirlia, "kirlia"},
        {PokemonName::Gardevoir, "gardevoir"},
        {PokemonName::Surskit, "surskit"},
        {PokemonName::Masquerain, "masquerain"},
        {PokemonName::Shroomish, "shroomish"},
        {PokemonName::Breloom, "breloom"},
        {PokemonName::Slakoth, "slakoth"},
        {PokemonName::Vigoroth, "vigoroth"},
        {PokemonName::Slaking, "slaking"},
        {PokemonName::Nincada, "nincada"},
        {PokemonName::Ninjask, "ninjask"},
        {PokemonName::Shedinja, "shedinja"},
        {PokemonName::Whismur, "whismur"},
        {PokemonName::Loudred, "loudred"},
        {PokemonName::Exploud, "exploud"},
        {PokemonName::Makuhita, "makuhita"},
        {PokemonName::Hariyama, "hariyama"},
        {PokemonName::Azurill, "azurill"},
        {PokemonName::Nosepass, "nosepass"},
        {PokemonName::Skitty, "skitty"},
        {PokemonName::Delcatty, "delcatty"},
        {PokemonName::Sableye, "sableye"},
        {PokemonName::Mawile, "mawile"},
        {PokemonName::Aron, "aron"},
        {PokemonName::Lairon, "lairon"},
        {PokemonName::Aggron, "aggron"},
        {PokemonName::Meditite, "meditite"},
        {PokemonName::Medicham, "medicham"},
        {PokemonName::Electrike, "electrike"},
        {PokemonName::Manectric, "manectric"},
        {PokemonName::Plusle, "plusle"},
        {PokemonName::Minun, "minun"},
        {PokemonName::Volbeat, "volbeat"},
        {PokemonName::Illumise, "illumise"},
        {PokemonName::Roselia, "roselia"},
        {PokemonName::Gulpin, "gulpin"},
        {PokemonName::Swalot, "swalot"},
        {PokemonName::Carvanha, "carvanha"},
        {PokemonName::Sharpedo, "sharpedo"},
        {PokemonName::Wailmer, "wailmer"},
        {PokemonName::Wailord, "wailord"},
        {PokemonName::Numel, "numel"},
        {PokemonName::Camerupt, "camerupt"},
        {PokemonName::Torkoal, "torkoal"},
        {PokemonName::Spoink, "spoink"},
        {PokemonName::Grumpig, "grumpig"},
        {PokemonName::Spinda, "spinda"},
        {PokemonName::Trapinch, "trapinch"},
        {PokemonName::Vibrava, "vibrava"},
        {PokemonName::Flygon, "flygon"},
        {PokemonName::Cacnea, "cacnea"},
        {PokemonName::Cacturne, "cacturne"},
        {PokemonName::Swablu, "swablu"},
        {PokemonName::Altaria, "altaria"},
        {PokemonName::Zangoose, "zangoose"},
        {PokemonName::Seviper, "seviper"},
        {PokemonName::Lunatone, "lunatone"},
        {PokemonName::Solrock, "solrock"},
        {PokemonName::Barboach, "barboach"},
        {PokemonName::Whiscash, "whiscash"},
        {PokemonName::Corphish, "corphish"},
        {PokemonName::Crawdaunt, "crawdaunt"},
        {PokemonName::Baltoy, "baltoy"},
        {PokemonName::Claydol, "claydol"},
        {PokemonName::Lileep, "lileep"},
        {PokemonName::Cradily, "cradily"},
        {PokemonName::Anorith, "anorith"},
        {PokemonName::Armaldo, "armaldo"},
        {PokemonName::Feebas, "feebas"},
        {PokemonName::Milotic, "milotic"},
        {PokemonName::Castform, "castform"},
        {PokemonName::Kecleon, "kecleon"},
        {PokemonName::Shuppet, "shuppet"},
        {PokemonName::Banette, "banette"},
        {PokemonName::Duskull, "duskull"},
        {PokemonName::Dusclops, "dusclops"},
        {PokemonName::Tropius, "tropius"},
        {PokemonName::Chimecho, "chimecho"},
        {PokemonName::Absol, "absol"},
        {PokemonName::Wynaut, "wynaut"},
        {PokemonName::Snorunt, "snorunt"},
        {PokemonName::Glalie, "glalie"},
        {PokemonName::Spheal, "spheal"},
        {PokemonName::Sealeo, "sealeo"},
        {PokemonName::Walrein, "walrein"},
        {PokemonName::Clamperl, "clamperl"},
        {PokemonName::Huntail, "huntail"},
        {PokemonName::Gorebyss, "gorebyss"},
        {PokemonName::Relicanth, "relicanth"},
        {PokemonName::Luvdisc, "luvdisc"},
        {PokemonName::Bagon, "bagon"},
        {PokemonName::Shelgon, "shelgon"},
        {PokemonName::Salamence, "salamence"},
        {PokemonName::Beldum, "beldum"},
        {PokemonName::Metang, "metang"},
        {PokemonName::Metagross, "metagross"},
        {PokemonName::Regirock, "regirock"},
        {PokemonName::Regice, "regice"},
        {PokemonName::Registeel, "registeel"},
        {PokemonName::Latias, "latias"},
        {PokemonName::Latios, "latios"},
        {PokemonName::Kyogre, "kyogre"},
        {PokemonName::Groudon, "groudon"},
        {PokemonName::Rayquaza, "rayquaza"},
        {PokemonName::Jirachi, "jirachi"},
        {PokemonName::Deoxys, "deoxys"},
        {PokemonName::Turtwig, "turtwig"},
        {PokemonName::Grotle, "grotle"},
        {PokemonName::Torterra, "torterra"},
        {PokemonName::Chimchar, "chimchar"},
        {PokemonName::Monferno, "monferno"},
        {PokemonName::Infernape, "infernape"},
        {PokemonName::Piplup, "piplup"},
        {PokemonName::Prinplup, "prinplup"},
        {PokemonName::Empoleon, "empoleon"},
        {PokemonName::Starly, "starly"},
        {PokemonName::Staravia, "staravia"},
        {PokemonName::Staraptor, "staraptor"},
        {PokemonName::Bidoof, "bidoof"},
        {PokemonName::Bibarel, "bibarel"},
        {PokemonName::Kricketot, "kricketot"},
        {PokemonName::Kricketune, "kricketune"},
        {PokemonName::Shinx, "shinx"},
        {PokemonName::Luxio, "luxio"},
        {PokemonName::Luxray, "luxray"},
        {PokemonName::Budew, "budew"},
        {PokemonName::Roserade, "roserade"},
        {PokemonName::Cranidos, "cranidos"},
        {PokemonName::Rampardos, "rampardos"},
        {PokemonName::Shieldon, "shieldon"},
        {PokemonName::Bastiodon, "bastiodon"},
        {PokemonName::Burmy, "burmy"},
        {PokemonName::Wormadam, "wormadam"},
        {PokemonName::Mothim, "mothim"},
        {PokemonName::Combee, "combee"},
        {PokemonName::Vespiquen, "vespiquen"},
        {PokemonName::Pachirisu, "pachirisu"},
        {PokemonName::Buizel, "buizel"},
        {PokemonName::Floatzel, "floatzel"},
        {PokemonName::Cherubi, "cherubi"},
        {PokemonName::Cherrim, "cherrim"},
        {PokemonName::Shellos, "shellos"},
        {PokemonName::Gastrodon, "gastrodon"},
        {PokemonName::Ambipom, "ambipom"},
        {PokemonName::Drifloon, "drifloon"},
        {PokemonName::Drifblim, "drifblim"},
        {PokemonName::Buneary, "buneary"},
        {PokemonName::Lopunny, "lopunny"},
        {PokemonName::Mismagius, "mismagius"},
        {PokemonName::Honchkrow, "honchkrow"},
        {PokemonName::Glameow, "glameow"},
        {PokemonName::Purugly, "purugly"},
        {PokemonName::Chingling, "chingling"},
        {PokemonName::Stunky, "stunky"},
        {PokemonName::Skuntank, "skuntank"},
        {PokemonName::Bronzor, "bronzor"},
        {PokemonName::Bronzong, "bronzong"},
        {PokemonName::Bonsly, "bonsly"},
        {PokemonName::MimeJr, "mimejr"},
        {PokemonName::Happiny, "happiny"},
        {PokemonName::Chatot, "chatot"},
        {PokemonName::Spiritomb, "spiritomb"},
        {PokemonName::Gible, "gible"},
        {PokemonName::Gabite, "gabite"},
        {PokemonName::Garchomp, "garchomp"},
        {PokemonName::Munchlax, "munchlax"},
        {PokemonName::Riolu, "riolu"},
        {PokemonName::Lucario, "lucario"},
        {PokemonName::Hippopotas, "hippopotas"},
        {PokemonName::Hippowdon, "hippowdon"},
        {PokemonName::Skorupi, "skorupi"},
        {PokemonName::Drapion, "drapion"},
        {PokemonName::Croagunk, "croagunk"},
        {PokemonName::Toxicroak, "toxicroak"},
        {PokemonName::Carnivine, "carnivine"},
        {PokemonName::Finneon, "finneon"},
        {PokemonName::Lumineon, "lumineon"},
        {PokemonName::Mantyke, "mantyke"},
        {PokemonName::Snover, "snover"},
        {PokemonName::Abomasnow, "abomasnow"},
        {PokemonName::Weavile, "weavile"},
        {PokemonName::Magnezone, "magnezone"},
        {PokemonName::Lickilicky, "lickilicky"},
        {PokemonName::Rhyperior, "rhyperior"},
        {PokemonName::Tangrowth, "tangrowth"},
        {PokemonName::Electivire, "electivire"},
        {PokemonName::Magmortar, "magmortar"},
        {PokemonName::Togekiss, "togekiss"},
        {PokemonName::Yanmega, "yanmega"},
        {PokemonName::Leafeon, "leafeon"},
        {PokemonName::Glaceon, "glaceon"},
        {PokemonName::Gliscor, "gliscor"},
        {PokemonName::Mamoswine, "mamoswine"},
        {PokemonName::PorygonZ, "porygonz"},
        {PokemonName::Gallade, "gallade"},
        {PokemonName::Probopass, "probopass"},
        {PokemonName::Dusknoir, "dusknoir"},
        {PokemonName::Froslass, "froslass"},
        {PokemonName::Rotom, "rotom"},
        {PokemonName::Uxie, "uxie"},
        {PokemonName::Mesprit, "mesprit"},
        {PokemonName::Azelf, "azelf"},
        {PokemonName::Dialga, "dialga"},
        {PokemonName::Palkia, "palkia"},
        {PokemonName::Heatran, "heatran"},
        {PokemonName::Regigigas, "regigigas"},
        {PokemonName::Giratina, "giratina"},
        {PokemonName::Cresselia, "cresselia"},
        {PokemonName::Phione, "phione"},
        {PokemonName::Manaphy, "manaphy"},
        {PokemonName::Darkrai, "darkrai"},
        {PokemonName::Shaymin, "shaymin"},
        {PokemonName::Arceus, "arceus"}
    };

    auto it = pokemonToString.find(p);
    if (it != pokemonToString.end()) {
        return it->second;
    } else {
        return "unknown";
    }
}

enum ExperienceGroup {
    MediumFast,
    Erratic,
    Fluctuating,
    MediumSlow,
    Fast,
    Slow,
    NumberOfExperienceGroups
};

inline ExperienceGroup getExperienceGroup(PokemonName p) {
    static const std::unordered_map<PokemonName, ExperienceGroup> pokemonToExperienceGroup = {
        {PokemonName::None, ExperienceGroup::NumberOfExperienceGroups},
        {PokemonName::Bulbasaur, ExperienceGroup::MediumSlow },
        {PokemonName::Ivysaur, ExperienceGroup::MediumSlow },
        {PokemonName::Venusaur, ExperienceGroup::MediumSlow },
        {PokemonName::Charmander, ExperienceGroup::MediumSlow },
        {PokemonName::Charmeleon, ExperienceGroup::MediumSlow },
        {PokemonName::Charizard, ExperienceGroup::MediumSlow },
        {PokemonName::Squirtle, ExperienceGroup::MediumSlow },
        {PokemonName::Wartortle, ExperienceGroup::MediumSlow },
        {PokemonName::Blastoise, ExperienceGroup::MediumSlow },
        {PokemonName::Caterpie, ExperienceGroup::MediumFast },
        {PokemonName::Metapod, ExperienceGroup::MediumFast },
        {PokemonName::Butterfree, ExperienceGroup::MediumFast },
        {PokemonName::Weedle, ExperienceGroup::MediumFast },
        {PokemonName::Kakuna, ExperienceGroup::MediumFast },
        {PokemonName::Beedrill, ExperienceGroup::MediumFast },
        {PokemonName::Pidgey, ExperienceGroup::MediumSlow },
        {PokemonName::Pidgeotto, ExperienceGroup::MediumSlow },
        {PokemonName::Pidgeot, ExperienceGroup::MediumSlow },
        {PokemonName::Rattata, ExperienceGroup::MediumFast },
        {PokemonName::Raticate, ExperienceGroup::MediumFast },
        {PokemonName::Spearow, ExperienceGroup::MediumFast },
        {PokemonName::Fearow, ExperienceGroup::MediumFast },
        {PokemonName::Ekans, ExperienceGroup::MediumFast },
        {PokemonName::Arbok, ExperienceGroup::MediumFast },
        {PokemonName::Pikachu, ExperienceGroup::MediumFast },
        {PokemonName::Raichu, ExperienceGroup::MediumFast },
        {PokemonName::Sandshrew, ExperienceGroup::MediumFast },
        {PokemonName::Sandslash, ExperienceGroup::MediumFast },
        {PokemonName::NidoranF, ExperienceGroup::MediumSlow },
        {PokemonName::Nidorina, ExperienceGroup::MediumSlow },
        {PokemonName::Nidoqueen, ExperienceGroup::MediumSlow },
        {PokemonName::NidoranM, ExperienceGroup::MediumSlow },
        {PokemonName::Nidorino, ExperienceGroup::MediumSlow },
        {PokemonName::Nidoking, ExperienceGroup::MediumSlow },
        {PokemonName::Clefairy, ExperienceGroup::Fast },
        {PokemonName::Clefable, ExperienceGroup::Fast },
        {PokemonName::Vulpix, ExperienceGroup::MediumFast },
        {PokemonName::Ninetales, ExperienceGroup::MediumFast },
        {PokemonName::Jigglypuff, ExperienceGroup::Fast },
        {PokemonName::Wigglytuff, ExperienceGroup::Fast },
        {PokemonName::Zubat, ExperienceGroup::MediumFast },
        {PokemonName::Golbat, ExperienceGroup::MediumFast },
        {PokemonName::Oddish, ExperienceGroup::MediumSlow },
        {PokemonName::Gloom, ExperienceGroup::MediumSlow },
        {PokemonName::Vileplume, ExperienceGroup::MediumSlow },
        {PokemonName::Paras, ExperienceGroup::MediumFast },
        {PokemonName::Parasect, ExperienceGroup::MediumFast },
        {PokemonName::Venonat, ExperienceGroup::MediumFast },
        {PokemonName::Venomoth, ExperienceGroup::MediumFast },
        {PokemonName::Diglett, ExperienceGroup::MediumFast },
        {PokemonName::Dugtrio, ExperienceGroup::MediumFast },
        {PokemonName::Meowth, ExperienceGroup::MediumFast },
        {PokemonName::Persian, ExperienceGroup::MediumFast },
        {PokemonName::Psyduck, ExperienceGroup::MediumFast },
        {PokemonName::Golduck, ExperienceGroup::MediumFast },
        {PokemonName::Mankey, ExperienceGroup::MediumFast },
        {PokemonName::Primeape, ExperienceGroup::MediumFast },
        {PokemonName::Growlithe, ExperienceGroup::Slow },
        {PokemonName::Arcanine, ExperienceGroup::Slow },
        {PokemonName::Poliwag, ExperienceGroup::MediumSlow },
        {PokemonName::Poliwhirl, ExperienceGroup::MediumSlow },
        {PokemonName::Poliwrath, ExperienceGroup::MediumSlow },
        {PokemonName::Abra, ExperienceGroup::MediumSlow },
        {PokemonName::Kadabra, ExperienceGroup::MediumSlow },
        {PokemonName::Alakazam, ExperienceGroup::MediumSlow },
        {PokemonName::Machop, ExperienceGroup::MediumSlow },
        {PokemonName::Machoke, ExperienceGroup::MediumSlow },
        {PokemonName::Machamp, ExperienceGroup::MediumSlow },
        {PokemonName::Bellsprout, ExperienceGroup::MediumSlow },
        {PokemonName::Weepinbell, ExperienceGroup::MediumSlow },
        {PokemonName::Victreebel, ExperienceGroup::MediumSlow },
        {PokemonName::Tentacool, ExperienceGroup::Slow },
        {PokemonName::Tentacruel, ExperienceGroup::Slow },
        {PokemonName::Geodude, ExperienceGroup::MediumSlow },
        {PokemonName::Graveler, ExperienceGroup::MediumSlow },
        {PokemonName::Golem, ExperienceGroup::MediumSlow },
        {PokemonName::Ponyta, ExperienceGroup::MediumFast },
        {PokemonName::Rapidash, ExperienceGroup::MediumFast },
        {PokemonName::Slowpoke, ExperienceGroup::MediumFast },
        {PokemonName::Slowbro, ExperienceGroup::MediumFast },
        {PokemonName::Magnemite, ExperienceGroup::MediumFast },
        {PokemonName::Magneton, ExperienceGroup::MediumFast },
        {PokemonName::Farfetchd, ExperienceGroup::MediumFast },
        {PokemonName::Doduo, ExperienceGroup::MediumFast },
        {PokemonName::Dodrio, ExperienceGroup::MediumFast },
        {PokemonName::Seel, ExperienceGroup::MediumFast },
        {PokemonName::Dewgong, ExperienceGroup::MediumFast },
        {PokemonName::Grimer, ExperienceGroup::MediumFast },
        {PokemonName::Muk, ExperienceGroup::MediumFast },
        {PokemonName::Shellder, ExperienceGroup::Slow },
        {PokemonName::Cloyster, ExperienceGroup::Slow },
        {PokemonName::Gastly, ExperienceGroup::MediumSlow },
        {PokemonName::Haunter, ExperienceGroup::MediumSlow },
        {PokemonName::Gengar, ExperienceGroup::MediumSlow },
        {PokemonName::Onix, ExperienceGroup::MediumFast },
        {PokemonName::Drowzee, ExperienceGroup::MediumFast },
        {PokemonName::Hypno, ExperienceGroup::MediumFast },
        {PokemonName::Krabby, ExperienceGroup::MediumFast },
        {PokemonName::Kingler, ExperienceGroup::MediumFast },
        {PokemonName::Voltorb, ExperienceGroup::MediumFast },
        {PokemonName::Electrode, ExperienceGroup::MediumFast },
        {PokemonName::Exeggcute, ExperienceGroup::Slow },
        {PokemonName::Exeggutor, ExperienceGroup::Slow },
        {PokemonName::Cubone, ExperienceGroup::MediumFast },
        {PokemonName::Marowak, ExperienceGroup::MediumFast },
        {PokemonName::Hitmonlee, ExperienceGroup::MediumFast },
        {PokemonName::Hitmonchan, ExperienceGroup::MediumFast },
        {PokemonName::Lickitung, ExperienceGroup::MediumFast },
        {PokemonName::Koffing, ExperienceGroup::MediumFast },
        {PokemonName::Weezing, ExperienceGroup::MediumFast },
        {PokemonName::Rhyhorn, ExperienceGroup::Slow },
        {PokemonName::Rhydon, ExperienceGroup::Slow },
        {PokemonName::Chansey, ExperienceGroup::Fast },
        {PokemonName::Tangela, ExperienceGroup::MediumFast },
        {PokemonName::Kangaskhan, ExperienceGroup::MediumFast },
        {PokemonName::Horsea, ExperienceGroup::MediumFast },
        {PokemonName::Seadra, ExperienceGroup::MediumFast },
        {PokemonName::Goldeen, ExperienceGroup::MediumFast },
        {PokemonName::Seaking, ExperienceGroup::MediumFast },
        {PokemonName::Staryu, ExperienceGroup::Slow },
        {PokemonName::Starmie, ExperienceGroup::Slow },
        {PokemonName::MrMime, ExperienceGroup::MediumFast },
        {PokemonName::Scyther, ExperienceGroup::MediumFast },
        {PokemonName::Jynx, ExperienceGroup::MediumFast },
        {PokemonName::Electabuzz, ExperienceGroup::MediumFast },
        {PokemonName::Magmar, ExperienceGroup::MediumFast },
        {PokemonName::Pinsir, ExperienceGroup::Slow },
        {PokemonName::Tauros, ExperienceGroup::Slow },
        {PokemonName::Magikarp, ExperienceGroup::Slow },
        {PokemonName::Gyarados, ExperienceGroup::Slow },
        {PokemonName::Lapras, ExperienceGroup::Slow },
        {PokemonName::Ditto, ExperienceGroup::MediumFast },
        {PokemonName::Eevee, ExperienceGroup::MediumFast },
        {PokemonName::Vaporeon, ExperienceGroup::MediumFast },
        {PokemonName::Jolteon, ExperienceGroup::MediumFast },
        {PokemonName::Flareon, ExperienceGroup::MediumFast },
        {PokemonName::Porygon, ExperienceGroup::MediumFast },
        {PokemonName::Omanyte, ExperienceGroup::MediumFast },
        {PokemonName::Omastar, ExperienceGroup::MediumFast },
        {PokemonName::Kabuto, ExperienceGroup::MediumFast },
        {PokemonName::Kabutops, ExperienceGroup::MediumFast },
        {PokemonName::Aerodactyl, ExperienceGroup::Slow },
        {PokemonName::Snorlax, ExperienceGroup::Slow },
        {PokemonName::Articuno, ExperienceGroup::Slow },
        {PokemonName::Zapdos, ExperienceGroup::Slow },
        {PokemonName::Moltres, ExperienceGroup::Slow },
        {PokemonName::Dratini, ExperienceGroup::Slow },
        {PokemonName::Dragonair, ExperienceGroup::Slow },
        {PokemonName::Dragonite, ExperienceGroup::Slow },
        {PokemonName::Mewtwo, ExperienceGroup::Slow },
        {PokemonName::Mew, ExperienceGroup::MediumSlow },
        {PokemonName::Chikorita, ExperienceGroup::MediumSlow },
        {PokemonName::Bayleef, ExperienceGroup::MediumSlow },
        {PokemonName::Meganium, ExperienceGroup::MediumSlow },
        {PokemonName::Cyndaquil, ExperienceGroup::MediumSlow },
        {PokemonName::Quilava, ExperienceGroup::MediumSlow },
        {PokemonName::Typhlosion, ExperienceGroup::MediumSlow },
        {PokemonName::Totodile, ExperienceGroup::MediumSlow },
        {PokemonName::Croconaw, ExperienceGroup::MediumSlow },
        {PokemonName::Feraligatr, ExperienceGroup::MediumSlow },
        {PokemonName::Sentret, ExperienceGroup::MediumFast },
        {PokemonName::Furret, ExperienceGroup::MediumFast },
        {PokemonName::Hoothoot, ExperienceGroup::MediumFast },
        {PokemonName::Noctowl, ExperienceGroup::MediumFast },
        {PokemonName::Ledyba, ExperienceGroup::Fast },
        {PokemonName::Ledian, ExperienceGroup::Fast },
        {PokemonName::Spinarak, ExperienceGroup::Fast },
        {PokemonName::Ariados, ExperienceGroup::Fast },
        {PokemonName::Crobat, ExperienceGroup::MediumFast },
        {PokemonName::Chinchou, ExperienceGroup::Slow },
        {PokemonName::Lanturn, ExperienceGroup::Slow },
        {PokemonName::Pichu, ExperienceGroup::MediumFast },
        {PokemonName::Cleffa, ExperienceGroup::Fast },
        {PokemonName::Igglybuff, ExperienceGroup::Fast },
        {PokemonName::Togepi, ExperienceGroup::Fast },
        {PokemonName::Togetic, ExperienceGroup::Fast },
        {PokemonName::Natu, ExperienceGroup::MediumFast },
        {PokemonName::Xatu, ExperienceGroup::MediumFast },
        {PokemonName::Mareep, ExperienceGroup::MediumSlow },
        {PokemonName::Flaaffy, ExperienceGroup::MediumSlow },
        {PokemonName::Ampharos, ExperienceGroup::MediumSlow },
        {PokemonName::Bellossom, ExperienceGroup::MediumSlow },
        {PokemonName::Marill, ExperienceGroup::Fast },
        {PokemonName::Azumarill, ExperienceGroup::Fast },
        {PokemonName::Sudowoodo, ExperienceGroup::MediumFast },
        {PokemonName::Politoed, ExperienceGroup::MediumSlow },
        {PokemonName::Hoppip, ExperienceGroup::MediumSlow },
        {PokemonName::Skiploom, ExperienceGroup::MediumSlow },
        {PokemonName::Jumpluff, ExperienceGroup::MediumSlow },
        {PokemonName::Aipom, ExperienceGroup::Fast },
        {PokemonName::Sunkern, ExperienceGroup::MediumSlow },
        {PokemonName::Sunflora, ExperienceGroup::MediumSlow },
        {PokemonName::Yanma, ExperienceGroup::MediumFast },
        {PokemonName::Wooper, ExperienceGroup::MediumFast },
        {PokemonName::Quagsire, ExperienceGroup::MediumFast },
        {PokemonName::Espeon, ExperienceGroup::MediumFast },
        {PokemonName::Umbreon, ExperienceGroup::MediumFast },
        {PokemonName::Murkrow, ExperienceGroup::MediumSlow },
        {PokemonName::Slowking, ExperienceGroup::MediumFast },
        {PokemonName::Misdreavus, ExperienceGroup::Fast },
        {PokemonName::Unown, ExperienceGroup::MediumFast },
        {PokemonName::Wobbuffet, ExperienceGroup::MediumFast },
        {PokemonName::Girafarig, ExperienceGroup::MediumFast },
        {PokemonName::Pineco, ExperienceGroup::MediumFast },
        {PokemonName::Forretress, ExperienceGroup::MediumFast },
        {PokemonName::Dunsparce, ExperienceGroup::MediumFast },
        {PokemonName::Gligar, ExperienceGroup::MediumSlow },
        {PokemonName::Steelix, ExperienceGroup::MediumFast },
        {PokemonName::Snubbull, ExperienceGroup::Fast },
        {PokemonName::Granbull, ExperienceGroup::Fast },
        {PokemonName::Qwilfish, ExperienceGroup::MediumFast },
        {PokemonName::Scizor, ExperienceGroup::MediumFast },
        {PokemonName::Shuckle, ExperienceGroup::MediumSlow },
        {PokemonName::Heracross, ExperienceGroup::Slow },
        {PokemonName::Sneasel, ExperienceGroup::MediumSlow },
        {PokemonName::Teddiursa, ExperienceGroup::MediumFast },
        {PokemonName::Ursaring, ExperienceGroup::MediumFast },
        {PokemonName::Slugma, ExperienceGroup::MediumFast },
        {PokemonName::Magcargo, ExperienceGroup::MediumFast },
        {PokemonName::Swinub, ExperienceGroup::Slow },
        {PokemonName::Piloswine, ExperienceGroup::Slow },
        {PokemonName::Corsola, ExperienceGroup::Fast },
        {PokemonName::Remoraid, ExperienceGroup::MediumFast },
        {PokemonName::Octillery, ExperienceGroup::MediumFast },
        {PokemonName::Delibird, ExperienceGroup::Fast },
        {PokemonName::Mantine, ExperienceGroup::Slow },
        {PokemonName::Skarmory, ExperienceGroup::Slow },
        {PokemonName::Houndour, ExperienceGroup::Slow },
        {PokemonName::Houndoom, ExperienceGroup::Slow },
        {PokemonName::Kingdra, ExperienceGroup::MediumFast },
        {PokemonName::Phanpy, ExperienceGroup::MediumFast },
        {PokemonName::Donphan, ExperienceGroup::MediumFast },
        {PokemonName::Porygon2, ExperienceGroup::MediumFast },
        {PokemonName::Stantler, ExperienceGroup::Slow },
        {PokemonName::Smeargle, ExperienceGroup::Fast },
        {PokemonName::Tyrogue, ExperienceGroup::MediumFast },
        {PokemonName::Hitmontop, ExperienceGroup::MediumFast },
        {PokemonName::Smoochum, ExperienceGroup::MediumFast },
        {PokemonName::Elekid, ExperienceGroup::MediumFast },
        {PokemonName::Magby, ExperienceGroup::MediumFast },
        {PokemonName::Miltank, ExperienceGroup::Slow },
        {PokemonName::Blissey, ExperienceGroup::Fast },
        {PokemonName::Raikou, ExperienceGroup::Slow },
        {PokemonName::Entei, ExperienceGroup::Slow },
        {PokemonName::Suicune, ExperienceGroup::Slow },
        {PokemonName::Larvitar, ExperienceGroup::Slow },
        {PokemonName::Pupitar, ExperienceGroup::Slow },
        {PokemonName::Tyranitar, ExperienceGroup::Slow },
        {PokemonName::Lugia, ExperienceGroup::Slow },
        {PokemonName::HoOh, ExperienceGroup::Slow },
        {PokemonName::Celebi, ExperienceGroup::MediumSlow },
        {PokemonName::Treecko, ExperienceGroup::MediumSlow },
        {PokemonName::Grovyle, ExperienceGroup::MediumSlow },
        {PokemonName::Sceptile, ExperienceGroup::MediumSlow },
        {PokemonName::Torchic, ExperienceGroup::MediumSlow },
        {PokemonName::Combusken, ExperienceGroup::MediumSlow },
        {PokemonName::Blaziken, ExperienceGroup::MediumSlow },
        {PokemonName::Mudkip, ExperienceGroup::MediumSlow },
        {PokemonName::Marshtomp, ExperienceGroup::MediumSlow },
        {PokemonName::Swampert, ExperienceGroup::MediumSlow },
        {PokemonName::Poochyena, ExperienceGroup::MediumFast },
        {PokemonName::Mightyena, ExperienceGroup::MediumFast },
        {PokemonName::Zigzagoon, ExperienceGroup::MediumFast },
        {PokemonName::Linoone, ExperienceGroup::MediumFast },
        {PokemonName::Wurmple, ExperienceGroup::MediumFast },
        {PokemonName::Silcoon, ExperienceGroup::MediumFast },
        {PokemonName::Beautifly, ExperienceGroup::MediumFast },
        {PokemonName::Cascoon, ExperienceGroup::MediumFast },
        {PokemonName::Dustox, ExperienceGroup::MediumFast },
        {PokemonName::Lotad, ExperienceGroup::MediumSlow },
        {PokemonName::Lombre, ExperienceGroup::MediumSlow },
        {PokemonName::Ludicolo, ExperienceGroup::MediumSlow },
        {PokemonName::Seedot, ExperienceGroup::MediumSlow },
        {PokemonName::Nuzleaf, ExperienceGroup::MediumSlow },
        {PokemonName::Shiftry, ExperienceGroup::MediumSlow },
        {PokemonName::Taillow, ExperienceGroup::MediumSlow },
        {PokemonName::Swellow, ExperienceGroup::MediumSlow },
        {PokemonName::Wingull, ExperienceGroup::MediumFast },
        {PokemonName::Pelipper, ExperienceGroup::MediumFast },
        {PokemonName::Ralts, ExperienceGroup::Slow },
        {PokemonName::Kirlia, ExperienceGroup::Slow },
        {PokemonName::Gardevoir, ExperienceGroup::Slow },
        {PokemonName::Surskit, ExperienceGroup::MediumFast },
        {PokemonName::Masquerain, ExperienceGroup::MediumFast },
        {PokemonName::Shroomish, ExperienceGroup::Fluctuating },
        {PokemonName::Breloom, ExperienceGroup::Fluctuating },
        {PokemonName::Slakoth, ExperienceGroup::Slow },
        {PokemonName::Vigoroth, ExperienceGroup::Slow },
        {PokemonName::Slaking, ExperienceGroup::Slow },
        {PokemonName::Nincada, ExperienceGroup::Erratic },
        {PokemonName::Ninjask, ExperienceGroup::Erratic },
        {PokemonName::Shedinja, ExperienceGroup::Erratic },
        {PokemonName::Whismur, ExperienceGroup::MediumSlow },
        {PokemonName::Loudred, ExperienceGroup::MediumSlow },
        {PokemonName::Exploud, ExperienceGroup::MediumSlow },
        {PokemonName::Makuhita, ExperienceGroup::Fluctuating },
        {PokemonName::Hariyama, ExperienceGroup::Fluctuating },
        {PokemonName::Azurill, ExperienceGroup::Fast },
        {PokemonName::Nosepass, ExperienceGroup::MediumFast },
        {PokemonName::Skitty, ExperienceGroup::Fast },
        {PokemonName::Delcatty, ExperienceGroup::Fast },
        {PokemonName::Sableye, ExperienceGroup::MediumSlow },
        {PokemonName::Mawile, ExperienceGroup::Fast },
        {PokemonName::Aron, ExperienceGroup::Slow },
        {PokemonName::Lairon, ExperienceGroup::Slow },
        {PokemonName::Aggron, ExperienceGroup::Slow },
        {PokemonName::Meditite, ExperienceGroup::MediumFast },
        {PokemonName::Medicham, ExperienceGroup::MediumFast },
        {PokemonName::Electrike, ExperienceGroup::Slow },
        {PokemonName::Manectric, ExperienceGroup::Slow },
        {PokemonName::Plusle, ExperienceGroup::MediumFast },
        {PokemonName::Minun, ExperienceGroup::MediumFast },
        {PokemonName::Volbeat, ExperienceGroup::Erratic },
        {PokemonName::Illumise, ExperienceGroup::Fluctuating },
        {PokemonName::Roselia, ExperienceGroup::MediumSlow },
        {PokemonName::Gulpin, ExperienceGroup::Fluctuating },
        {PokemonName::Swalot, ExperienceGroup::Fluctuating },
        {PokemonName::Carvanha, ExperienceGroup::Slow },
        {PokemonName::Sharpedo, ExperienceGroup::Slow },
        {PokemonName::Wailmer, ExperienceGroup::Fluctuating },
        {PokemonName::Wailord, ExperienceGroup::Fluctuating },
        {PokemonName::Numel, ExperienceGroup::MediumFast },
        {PokemonName::Camerupt, ExperienceGroup::MediumFast },
        {PokemonName::Torkoal, ExperienceGroup::MediumFast },
        {PokemonName::Spoink, ExperienceGroup::Fast },
        {PokemonName::Grumpig, ExperienceGroup::Fast },
        {PokemonName::Spinda, ExperienceGroup::Fast },
        {PokemonName::Trapinch, ExperienceGroup::MediumSlow },
        {PokemonName::Vibrava, ExperienceGroup::MediumSlow },
        {PokemonName::Flygon, ExperienceGroup::MediumSlow },
        {PokemonName::Cacnea, ExperienceGroup::MediumSlow },
        {PokemonName::Cacturne, ExperienceGroup::MediumSlow },
        {PokemonName::Swablu, ExperienceGroup::Erratic },
        {PokemonName::Altaria, ExperienceGroup::Erratic },
        {PokemonName::Zangoose, ExperienceGroup::Erratic },
        {PokemonName::Seviper, ExperienceGroup::Fluctuating },
        {PokemonName::Lunatone, ExperienceGroup::Fast },
        {PokemonName::Solrock, ExperienceGroup::Fast },
        {PokemonName::Barboach, ExperienceGroup::MediumFast },
        {PokemonName::Whiscash, ExperienceGroup::MediumFast },
        {PokemonName::Corphish, ExperienceGroup::Fluctuating },
        {PokemonName::Crawdaunt, ExperienceGroup::Fluctuating },
        {PokemonName::Baltoy, ExperienceGroup::MediumFast },
        {PokemonName::Claydol, ExperienceGroup::MediumFast },
        {PokemonName::Lileep, ExperienceGroup::Erratic },
        {PokemonName::Cradily, ExperienceGroup::Erratic },
        {PokemonName::Anorith, ExperienceGroup::Erratic },
        {PokemonName::Armaldo, ExperienceGroup::Erratic },
        {PokemonName::Feebas, ExperienceGroup::Erratic },
        {PokemonName::Milotic, ExperienceGroup::Erratic },
        {PokemonName::Castform, ExperienceGroup::MediumFast },
        {PokemonName::Kecleon, ExperienceGroup::MediumSlow },
        {PokemonName::Shuppet, ExperienceGroup::Fast },
        {PokemonName::Banette, ExperienceGroup::Fast },
        {PokemonName::Duskull, ExperienceGroup::Fast },
        {PokemonName::Dusclops, ExperienceGroup::Fast },
        {PokemonName::Tropius, ExperienceGroup::Slow },
        {PokemonName::Chimecho, ExperienceGroup::Fast },
        {PokemonName::Absol, ExperienceGroup::MediumSlow },
        {PokemonName::Wynaut, ExperienceGroup::MediumFast },
        {PokemonName::Snorunt, ExperienceGroup::MediumFast },
        {PokemonName::Glalie, ExperienceGroup::MediumFast },
        {PokemonName::Spheal, ExperienceGroup::MediumSlow },
        {PokemonName::Sealeo, ExperienceGroup::MediumSlow },
        {PokemonName::Walrein, ExperienceGroup::MediumSlow },
        {PokemonName::Clamperl, ExperienceGroup::Erratic },
        {PokemonName::Huntail, ExperienceGroup::Erratic },
        {PokemonName::Gorebyss, ExperienceGroup::Erratic },
        {PokemonName::Relicanth, ExperienceGroup::Slow },
        {PokemonName::Luvdisc, ExperienceGroup::Fast },
        {PokemonName::Bagon, ExperienceGroup::Slow },
        {PokemonName::Shelgon, ExperienceGroup::Slow },
        {PokemonName::Salamence, ExperienceGroup::Slow },
        {PokemonName::Beldum, ExperienceGroup::Slow },
        {PokemonName::Metang, ExperienceGroup::Slow },
        {PokemonName::Metagross, ExperienceGroup::Slow },
        {PokemonName::Regirock, ExperienceGroup::Slow },
        {PokemonName::Regice, ExperienceGroup::Slow },
        {PokemonName::Registeel, ExperienceGroup::Slow },
        {PokemonName::Latias, ExperienceGroup::Slow },
        {PokemonName::Latios, ExperienceGroup::Slow },
        {PokemonName::Kyogre, ExperienceGroup::Slow },
        {PokemonName::Groudon, ExperienceGroup::Slow },
        {PokemonName::Rayquaza, ExperienceGroup::Slow },
        {PokemonName::Jirachi, ExperienceGroup::Slow },
        {PokemonName::Deoxys, ExperienceGroup::Slow },
        {PokemonName::Turtwig, ExperienceGroup::MediumSlow },
        {PokemonName::Grotle, ExperienceGroup::MediumSlow },
        {PokemonName::Torterra, ExperienceGroup::MediumSlow },
        {PokemonName::Chimchar, ExperienceGroup::MediumSlow },
        {PokemonName::Monferno, ExperienceGroup::MediumSlow },
        {PokemonName::Infernape, ExperienceGroup::MediumSlow },
        {PokemonName::Piplup, ExperienceGroup::MediumSlow },
        {PokemonName::Prinplup, ExperienceGroup::MediumSlow },
        {PokemonName::Empoleon, ExperienceGroup::MediumSlow },
        {PokemonName::Starly, ExperienceGroup::MediumSlow },
        {PokemonName::Staravia, ExperienceGroup::MediumSlow },
        {PokemonName::Staraptor, ExperienceGroup::MediumSlow },
        {PokemonName::Bidoof, ExperienceGroup::MediumFast },
        {PokemonName::Bibarel, ExperienceGroup::MediumFast },
        {PokemonName::Kricketot, ExperienceGroup::MediumSlow },
        {PokemonName::Kricketune, ExperienceGroup::MediumSlow },
        {PokemonName::Shinx, ExperienceGroup::MediumSlow },
        {PokemonName::Luxio, ExperienceGroup::MediumSlow },
        {PokemonName::Luxray, ExperienceGroup::MediumSlow },
        {PokemonName::Budew, ExperienceGroup::MediumSlow },
        {PokemonName::Roserade, ExperienceGroup::MediumSlow },
        {PokemonName::Cranidos, ExperienceGroup::Erratic },
        {PokemonName::Rampardos, ExperienceGroup::Erratic },
        {PokemonName::Shieldon, ExperienceGroup::Erratic },
        {PokemonName::Bastiodon, ExperienceGroup::Erratic },
        {PokemonName::Burmy, ExperienceGroup::MediumFast },
        {PokemonName::Wormadam, ExperienceGroup::MediumFast },
        {PokemonName::Mothim, ExperienceGroup::MediumFast },
        {PokemonName::Combee, ExperienceGroup::MediumSlow },
        {PokemonName::Vespiquen, ExperienceGroup::MediumSlow },
        {PokemonName::Pachirisu, ExperienceGroup::MediumFast },
        {PokemonName::Buizel, ExperienceGroup::MediumFast },
        {PokemonName::Floatzel, ExperienceGroup::MediumFast },
        {PokemonName::Cherubi, ExperienceGroup::MediumFast },
        {PokemonName::Cherrim, ExperienceGroup::MediumFast },
        {PokemonName::Shellos, ExperienceGroup::MediumFast },
        {PokemonName::Gastrodon, ExperienceGroup::MediumFast },
        {PokemonName::Ambipom, ExperienceGroup::Fast },
        {PokemonName::Drifloon, ExperienceGroup::Fluctuating },
        {PokemonName::Drifblim, ExperienceGroup::Fluctuating },
        {PokemonName::Buneary, ExperienceGroup::MediumFast },
        {PokemonName::Lopunny, ExperienceGroup::MediumFast },
        {PokemonName::Mismagius, ExperienceGroup::Fast },
        {PokemonName::Honchkrow, ExperienceGroup::MediumSlow },
        {PokemonName::Glameow, ExperienceGroup::Fast },
        {PokemonName::Purugly, ExperienceGroup::Fast },
        {PokemonName::Chingling, ExperienceGroup::Fast },
        {PokemonName::Stunky, ExperienceGroup::MediumFast },
        {PokemonName::Skuntank, ExperienceGroup::MediumFast },
        {PokemonName::Bronzor, ExperienceGroup::MediumFast },
        {PokemonName::Bronzong, ExperienceGroup::MediumFast },
        {PokemonName::Bonsly, ExperienceGroup::MediumFast },
        {PokemonName::MimeJr, ExperienceGroup::MediumFast },
        {PokemonName::Happiny, ExperienceGroup::Fast },
        {PokemonName::Chatot, ExperienceGroup::MediumSlow },
        {PokemonName::Spiritomb, ExperienceGroup::MediumFast },
        {PokemonName::Gible, ExperienceGroup::Slow },
        {PokemonName::Gabite, ExperienceGroup::Slow },
        {PokemonName::Garchomp, ExperienceGroup::Slow },
        {PokemonName::Munchlax, ExperienceGroup::Slow },
        {PokemonName::Riolu, ExperienceGroup::MediumSlow },
        {PokemonName::Lucario, ExperienceGroup::MediumSlow },
        {PokemonName::Hippopotas, ExperienceGroup::Slow },
        {PokemonName::Hippowdon, ExperienceGroup::Slow },
        {PokemonName::Skorupi, ExperienceGroup::Slow },
        {PokemonName::Drapion, ExperienceGroup::Slow },
        {PokemonName::Croagunk, ExperienceGroup::MediumFast },
        {PokemonName::Toxicroak, ExperienceGroup::MediumFast },
        {PokemonName::Carnivine, ExperienceGroup::Slow },
        {PokemonName::Finneon, ExperienceGroup::Erratic },
        {PokemonName::Lumineon, ExperienceGroup::Erratic },
        {PokemonName::Mantyke, ExperienceGroup::Slow },
        {PokemonName::Snover, ExperienceGroup::Slow },
        {PokemonName::Abomasnow, ExperienceGroup::Slow },
        {PokemonName::Weavile, ExperienceGroup::MediumSlow },
        {PokemonName::Magnezone, ExperienceGroup::MediumFast },
        {PokemonName::Lickilicky, ExperienceGroup::MediumFast },
        {PokemonName::Rhyperior, ExperienceGroup::Slow },
        {PokemonName::Tangrowth, ExperienceGroup::MediumFast },
        {PokemonName::Electivire, ExperienceGroup::MediumFast },
        {PokemonName::Magmortar, ExperienceGroup::MediumFast },
        {PokemonName::Togekiss, ExperienceGroup::Fast },
        {PokemonName::Yanmega, ExperienceGroup::MediumFast },
        {PokemonName::Leafeon, ExperienceGroup::MediumFast },
        {PokemonName::Glaceon, ExperienceGroup::MediumFast },
        {PokemonName::Gliscor, ExperienceGroup::MediumSlow },
        {PokemonName::Mamoswine, ExperienceGroup::Slow },
        {PokemonName::PorygonZ, ExperienceGroup::MediumFast },
        {PokemonName::Gallade, ExperienceGroup::Slow },
        {PokemonName::Probopass, ExperienceGroup::MediumFast },
        {PokemonName::Dusknoir, ExperienceGroup::Fast },
        {PokemonName::Froslass, ExperienceGroup::MediumFast },
        {PokemonName::Rotom, ExperienceGroup::MediumFast },
        {PokemonName::Uxie, ExperienceGroup::Slow },
        {PokemonName::Mesprit, ExperienceGroup::Slow },
        {PokemonName::Azelf, ExperienceGroup::Slow },
        {PokemonName::Dialga, ExperienceGroup::Slow },
        {PokemonName::Palkia, ExperienceGroup::Slow },
        {PokemonName::Heatran, ExperienceGroup::Slow },
        {PokemonName::Regigigas, ExperienceGroup::Slow },
        {PokemonName::Giratina, ExperienceGroup::Slow },
        {PokemonName::Cresselia, ExperienceGroup::Slow },
        {PokemonName::Phione, ExperienceGroup::Slow },
        {PokemonName::Manaphy, ExperienceGroup::Slow },
        {PokemonName::Darkrai, ExperienceGroup::Slow },
        {PokemonName::Shaymin, ExperienceGroup::MediumSlow },
        {PokemonName::Arceus, ExperienceGroup::Slow },
    };

    auto it = pokemonToExperienceGroup.find(p);
    if (it != pokemonToExperienceGroup.end()) {
        return it->second;
    } else {
        return ExperienceGroup::NumberOfExperienceGroups;
    }
}